### ISSUE TITLE
是不是应该加个卸载插件的方法呢？

### ISSUE THREAD

**Issue by shicaiD** [didi/VirtualAPK#100]
关闭宿主进程，打开宿主，会重新加载插件。
若是没有关闭宿主进程，而插件更新了，宿主不会重新加载插件，我也没找到有重新加载插件的方法。
尝试重新加载，发现这里LoadedPlugin(PluginManager pluginManager, Context context, File apk)有：``
` if (pluginManager.getLoadedPlugin(mPackageInfo.packageName) != null) { `
            `      throw new RuntimeException("plugin has already been loaded : " + mPackageInfo.packageName); `
        ` } `
所以我想，是不是要加个从mPlugins中卸载某个插件的方法或者重新加载某个插件的方法呢？ 
😊

**Comment by luying6** [comment]
可以通过服务器管理插件，封装个插件管理类，根据服务器请求结果做这些操作

**Comment by HuChundong** [comment]
VA不支持热卸载，必须重启app重新加载新版本的插件吗？

**Comment by luying6** [comment]
DexClassLoader并不能直接加载外部存储的.dex文件，而是要先拷贝到内部存储里.所以当你下载了新的插件，旧的插件其实已经被覆盖了，只是需要重新加载将外部的.dex拷贝进内部存储里

**Comment by shicaiD** [comment]
@luying6 是的没错，DexClassLoader是会重新加载并覆盖旧插件，但现在我们遇到的问题是，要关闭app，重新打开才能重新加载。
@HuChundong  官方目前没有提供你说的热卸载，我是用反射暂时处理，反射拿到PluginManager的mPlugin，把插件remove掉，DexClassLoader就能加载覆盖原先的.dex来实现热卸载，可供参考。

**Comment by luying6** [comment]
@shicaiD 你是怎样进行插件版本管理的，是application里面一次性进行插件版本对比还是加载的时候请求后端检查插件版本然后再更新的？

**Comment by shicaiD** [comment]
@luying6 暂时还没有涉及到，但是你说的两种都一样是要打开app再检查更新，难道更新插件一定要重启app吗😓

**Comment by shicaiD** [comment]
@luying6  理解了你意思，thx

**Comment by AlaphZhu** [comment]
pluginManager.getAllLoadedPlugins().remove(loadedPlugin)
这样应可以实现卸载

**Comment by EarlyLau** [comment]
> DexClassLoader并不能直接加载外部存储的.dex文件，而是要先拷贝到内部存储里.所以当你下载了新的插件，旧的插件其实已经被覆盖了，只是需要重新加载将外部的.dex拷贝进内部存储里

我也是这样做的，为什么新插件加载后，没有把旧的插件覆盖，宿主跳转后显示的是旧插件，难道还需要进行其它操作吗？

**Comment by izxyz** [comment]
@zxc0809 不可以这样卸载, 只能反射拿到mPlugins
