### ISSUE TITLE
VA如何将插件apk中资源ID的packageid改为 0x6f 的？

### ISSUE THREAD

**Issue by PeterXiaoWang** [didi/VirtualAPK#102]
如题，这部分是在gradle插件中完成的吗？

**Comment by shicaiD** [comment]
插件build.gradle后加：
virtualApk {
    packageId = 0x6f             // The package id of Resources.
    targetHost='../Host/app' // The path of application module in host project.
    applyHostMapping = true      // [Optional] Default value is true.
}

**Comment by PeterXiaoWang** [comment]
我是想知道插件实现改资源ID的packageid的原理。。不知道是否会开源插件

**Comment by singwhatiwanna** [comment]
@PeterXiaoWang 会开源的，在整理中。

**Comment by fanOfDemo** [comment]
看到了我想问的问题，期待开源这个独立功能的插件！

**Comment by cmeiyuan** [comment]
我自己写了个修改packageId的方法：
https://github.com/cmeiyuan/ArscEditor/blob/master/src/com/cmy/parser/ResTableEditor.java

**Comment by vhly** [comment]
AAPT 打包资源时 resources.asrc 中，每一个应用程序都会分配一个 packageId，默认为 0x7F 这就是为什么看到 R.java 中都是 0x7F 开头的了。如果手动修改了这个文件，并且将 R.java 同步，就可以改了哦，还有网上说为什么不能为 0x01，因为这个是Android系统包 资源前缀，也就是 0x01xxxxxx，都是系统的
