### ISSUE TITLE
插件如果要依赖别的模块只能通过aar的方式吗？

### ISSUE THREAD

**Issue by luying6** [didi/VirtualAPK#103]
如果依赖aar，那我每次打插件apk的时候都要，rebuild依赖的模块然后手动将aar文件粘贴到我的lib里面，是这样理解的吗？

**Comment by singwhatiwanna** [comment]
aar或者module其实都可以的

**Comment by luying6** [comment]
@singwhatiwanna 刚哥，我发现插件依赖了和宿主一样的module后，打插件的时候module里面的依赖比如glide，比如okhttp等又下载了一份，只有res下的资源文件合并了

**Comment by superqiaopu** [comment]
去重只支持 maven 依赖，本地使用可以把module导出aar至 local maven。
