### ISSUE TITLE
大神您好，请问VirtualAPK是否支持WindowManager

### ISSUE THREAD

**Issue by xshasha521** [didi/VirtualAPK#104]
大神您好，请问VirtualAPK是否支持WindowManager？
1. 插件程序单独运行正常。
2. 将其与插件宿主gradle编译，正确，然后使用宿主加载插件程序报错：
[ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
ActivityThread: AppLock checkAppLockState isAppLocked = false pkgName = com.didi.virtualapk showWhenLocked = false
我尝试了几次，只要使用WindowManager，插件程序就会报错闪退，不使用WindowManager，运行正常
（SYSTEM_ALERT_WINDOW权限配置是正确的）

耗了很长时间也没有解决这个问题，请大神指点，万分感谢！！！

**Comment by XiuLin** [comment]
您好 ，您留一个QQ我加您吧。或者您在官方群里提问 就行。把demo一并发出来。
