### ISSUE TITLE
点击“加载插件”，直接报异常

### ISSUE THREAD

**Issue by question888** [didi/VirtualAPK#105]
FATAL EXCEPTION: main
 Process: com.didi.virtualapk, PID: 23935
java.lang.IncompatibleClassChangeError: Structural change of android.support.v7.app.AppCompatActivity is hazardous (/data/user/0/com.didi.virtualapk/app_dex/Test.dex at compile time, /data/app/com.didi.virtualapk-2/oat/arm/base.odex at runtime): Virtual method count off: 44 vs 36

**Comment by XiuLin** [comment]
你看看你项目中所有的v7版本是不是和CoreLibrary中一致。

**Comment by focuseyes360** [comment]
很明显是宿主和插件的引用包不一致导致的，上周刚解决这个问题，比较发现运行的插件比宿主多了5行代码

**Comment by LiWeiQiangAndroid** [comment]
和混淆也有关
