### ISSUE TITLE
Host project sync with gradle error for Android Studio 3

### ISSUE THREAD

**Issue by jay-cheung** [didi/VirtualAPK#111]
Error:Execution failed for task ':app:processDebugResources'.
> Could not get unknown property 'textSymbolOutputDir' for task ':app:processDebugResources' of type com.android.build.gradle.tasks.ProcessAndroidResources.

**Comment by XiuLin** [comment]
构建请使用官方要求的版本这个和android studio的版本没有关系。

**Comment by zac4j** [comment]
I try a lower version gradle file(gradle-3.3-all.zip) with `classpath 'com.android.tools.build:gradle:2.3.3'` in project's build.gradle file and solved my problem.
