### ISSUE TITLE
gradle clean assemblePlugin

### ISSUE THREAD

**Issue by suzhen0910101217** [didi/VirtualAPK#114]
Execution failed for task ':WizarposPaymentHandUI:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536，插件工程里面引用了MultiDexApplication还是65536,是不是冲突啊

**Comment by XiuLin** [comment]
插件 不支持 这种超过 65536的。
