### ISSUE TITLE
启动插件中的Activity

### ISSUE THREAD

**Issue by yc654084303** [didi/VirtualAPK#115]
`if (PluginManager.getInstance(this).getLoadedPlugin("com.yc.android.appplugin") == null) {
            Toast.makeText(getApplicationContext(), "插件未加载,请尝试重启APP", Toast.LENGTH_SHORT).show();
            return;
        }
        Intent intent = new Intent();
        intent.putExtra("plugin","主工程Intent数据");
        intent.setClassName("com.yc.android.appplugin", "com.yc.android.appplugin.MainPluginActivity");
        startActivity(intent);
    }`
   这样跳转，但是在插件中获取不到intent中的数据；是不支持嘛？？

**Comment by XiuLin** [comment]
这是完全支持的。可能您在构建或者哪里出了一些问题
