### ISSUE TITLE
插件包中的png图片都显示黑色

### ISSUE THREAD

**Issue by chenhui3014** [didi/VirtualAPK#116]
插件包可以正常生成，但是发现apk包中的图片（png格式） 都是显示黑色的。请问这算是bug吗？
![image](https://user-images.githubusercontent.com/10879711/29954136-334c100e-8f08-11e7-9f5a-3baa25cbf7e3.png)

**Comment by XiuLin** [comment]
请您留下QQ或者到官方群中交流 最好把demo一并发出来 我这看看。

**Comment by XiuLin** [comment]
在gradle中配置shrinkResources true

**Comment by chenhui3014** [comment]
谢谢，已经解决，原因是build.gradle 中配置 shrinkResources true，资源文件有没有被引用，导致图片被压缩导致
