### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by xh2009cn** [didi/VirtualAPK#123]
插件调用ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.CAMERA}, 100)方法时报错：
java.lang.AbstractMethodError: abstract method "java.lang.String android.content.pm.PackageManager.getPermissionControllerPackageName()"

是不是插件的PackageManager找不到实现的类

**Comment by 12og3r** [comment]
look at this commit～
https://github.com/didi/VirtualAPK/pull/384
