### ISSUE TITLE
appcompat-v7:22.2.0这个依赖宿主和插件无法达成一致，怎么办？还有没有协调的办法 呢？

### ISSUE THREAD

**Issue by helloworkcupid** [didi/VirtualAPK#124]
宿主项目，需要appcompat-v7:24.2.1，插件可能需要23.1.0，这都无法协调了感觉，除非都调高的版本

**Comment by singwhatiwanna** [comment]
@helloworkcupid 这个请做到版本一致。换个角度，假如宿主和插件的代码是在一个工程中，那么你显然没办法同时使用不同版本的appcompat，最终构建的时候Gradle默认会选择最新的appcompat版本。
