### ISSUE TITLE
关于Activity 的screenOriention的bug

### ISSUE THREAD

**Issue by pngfi** [didi/VirtualAPK#125]
发现一个关于Activity 的 screenOrientation 的一个bug：
正常情况下 比如我有一个界面需要横屏，我在manifest文件中指定
 android:screenOrientation="landscape"
这种情况Activity在创建的时候就会设定它的screenOrientation，生命周期只会走一次。

而我发现va是在activity创建完之后才重新设定
@Override
    public void callActivityOnCreate(Activity activity, Bundle icicle) {
        final Intent intent = activity.getIntent();
        if (PluginUtil.isIntentFromPlugin(intent)) {
            Context base = activity.getBaseContext();
            try {
                LoadedPlugin plugin = this.mPluginManager.getLoadedPlugin(intent);
                ReflectUtil.setField(base.getClass(), base, "mResources", plugin.getResources());
                ReflectUtil.setField(ContextWrapper.class, activity, "mBase", plugin.getPluginContext());
                ReflectUtil.setField(Activity.class, activity, "mApplication", plugin.getApplication());
                ReflectUtil.setFieldNoException(ContextThemeWrapper.class, activity, "mBase", plugin.getPluginContext());
                ActivityInfo activityInfo = plugin.getActivityInfo(PluginUtil.getComponent(intent));
                if (activityInfo.screenOrientation != ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED) {
                    activity.setRequestedOrientation(activityInfo.screenOrientation);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

        mBase.callActivityOnCreate(activity, icicle);
    }
有一个问题就是调用setRequestedOrientation(activityInfo.screenOrientation);这个方法如果改变了屏幕方向，会导致Activity的销毁和重建，这样就与Android系统本身的情况不一致了。

为什么大家现在还没有发现这个bug呢？或者说那为什么在xml中设置了android:screenOrientation="portaint"时候不会出现这样的错误呢？
因为坑位中没有去指定screenOrientation 的值，即默认值为“unspecified”，由系统选择方向。在不同设备上，系统使用的政策以及基于政策在特定上下文所做的选择可能有所差异。但是我实验应该大多数情况下创建的都是一个竖屏的Activty,这时候你去调用setRequestedOrientation(activityInfo.screenOrientation);并没又改变屏幕的方向，所以没有引起Activity重建。

 可一旦你设置了横屏，那么问题就来了，Activty会重建。

因此还是希望官方能够早日设计出一套完美的坑位方案以完美支持screenOriention ，另外希望支持configChanges 。

**Comment by singwhatiwanna** [comment]
你提的建议很好，configChanges不太好支持，你可以尝试在占坑的Activity中指定configChanges
