### ISSUE TITLE
插件用gradlew clean assemblePlugin编译后没有剔除公共的部分，在宿主插件上运行不起来

### ISSUE THREAD

**Issue by clarajuan** [didi/VirtualAPK#127]
插件用gradlew clean assemblePlugin编译后没有剔除公共的部分，在宿主上运行不起来，
我用window操作系统编译的。

相同代码用mac操作系统编译能剔除公共资源，并能在宿主中运行

请问两个操作系统编译有什么要注意的吗？

**Comment by XiuLin** [comment]
这个构建是依托于gradle实现的。应该和所在os没有关系。您可以看看是不是有其他的差异。
