### ISSUE TITLE
宿主 跳转插件的时候，跳转的还是当前页面

### ISSUE THREAD

**Issue by vonions** [didi/VirtualAPK#129]

**Comment by vonions** [comment]
Intent intent = new Intent();
                intent.setClassName("cc.com.vapk", "cc.com.vapk.MainActivity");
                startActivity(intent);
  我在宿主跳转插件的时候，如上，跳转的还是当前页面的Activity，并且有跳转动作

**Comment by singwhatiwanna** [comment]
@vonions 这是不可能的，请提供更多的信息吧

**Comment by vonions** [comment]
宿主项目app  build配置，
apply plugin: 'com.didi.virtualapk.host'
compile 'com.didi.virtualapk:core:0.9.0'
工程 的build 配置 
classpath 'com.didi.virtualapk:gradle:0.9.0'

JAVA文件 
在Application
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        PluginManager.getInstance(base).init();
    }

在Activity
   String pluginPath = Environment.getExternalStorageDirectory().getAbsolutePath().concat("/a.apk");
        File plugin = new File(pluginPath);
        try {
            PluginManager.getInstance(getBaseContext()).loadPlugin(plugin);
        } catch (Exception e) {
            e.printStackTrace();
        }


        findViewById(R.id.bt).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent();
                intent.setClassName("cc.com.vapk", "cc.com.vapk.MainActivity");
                startActivity(intent);


            }
        });

在插件APP  build 里
apply plugin: 'com.didi.virtualapk.plugin'

virtualApk {
    packageId = 0x1f             // The package id of Resources.
    targetHost='E:/MagicCamera-master/MagicCamera-master/VirtualApk/app' // The path of application module in host project.
    applyHostMapping = true      // [Optional] Default value is true.
}

工程的build 里  
classpath 'com.didi.virtualapk:gradle:0.9.0'

然后Activity里边什么都没写，就是一个默认的布局
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

请帮我分析一波原因吧

**Comment by singwhatiwanna** [comment]
R.layout.activity_main，这个布局文件，是否宿主工程中也有一份？

**Comment by vonions** [comment]
没有，我的宿主的  布局文件 是 setContentView(R.layout.activity_main11);  

宿主只有一个R.layout.activity_main11

**Comment by liujinchao** [comment]
@vonions 可能是你的插件生成方式有问题，不要拿build->outputs -> apk目录下的apk，而是取build -> outputs -> plugin ->release目录下的apk，生成方式gradle clean assemblePlugin或者./gradlew clean assemblePlugin

**Comment by yoyiyi** [comment]
@vonions 解决了没有，我的也这样，并没有跳转到插件主页，还是跳转到宿主的主页，有跳转过渡动画

**Comment by vonions** [comment]
没有，我就试了试不能用我就没试了

**Comment by keven0632** [comment]
使用 gradlew clean assemblePlugin 生成插件，或者用 AndroidStudio 右侧的 Gradle 按钮下的插件工程下的 assemblePlugin 按钮生成插件，先要 build 宿主一下，然后再生成插件

**Comment by weizai** [comment]
> 使用 gradlew clean assemblePlugin 生成插件，或者用 AndroidStudio 右侧的 Gradle 按钮下的插件工程下的 assemblePlugin 按钮生成插件，先要 build 宿主一下，然后再生成插件

总结下:

**Comment by weizai** [comment]
> 使用 gradlew clean assemblePlugin 生成插件，或者用 AndroidStudio 右侧的 Gradle 按钮下的插件工程下的 assemblePlugin 按钮生成插件，先要 build 宿主一下，然后再生成插件

总结下:
1. 先将宿主build
2. 注意资源名称不要和宿主重复, 比如layout_main.xml
3. 在插件module中,  Gradle task选择assemblePlugin，注意不是_assemblePlugin, 我当时就是因为这个下划线

good luck~

**Comment by sazewdfcvg16** [comment]
解决了吗？ 我也试试了，也出现了，主要是资源加载问题，packageId 也换了好几个值，都不行，检测也都没错

**Comment by sazewdfcvg16** [comment]
解决了吗？ 应该和我这情况一样，主要是资源加载问题，packageId 也换了好几个值，都不行，都是按照demo配置来的，加了调试代码如下，资源id找不到，应该是资源没有加载导致的。
@Override
    protected void onResume() {
        super.onResume();
        try {
            TextView plugTv = findViewById(R.id.plug_tv);
            if(plugTv != null) {
                plugTv.setText("Plugin Activity TextView");
            }else {
                Log.e("PlugMainActivity", "PlugMainActivity->onResume plugTv = null ");
            }
        }catch (Exception e){
            Log.e("PlugMainActivity", e.toString());
        }
        Log.e("PlugMainActivity", "PlugMainActivity->onResume ..");
    }

E/PlugMainActivity: PlugMainActivity->onCreate ..
E/PlugMainActivity: PlugMainActivity->onResume plugTv = null 
E/PlugMainActivity: PlugMainActivity->onResume ..
