### ISSUE TITLE
缺少gradle插件部分代码

### ISSUE THREAD

**Issue by zacklpx** [didi/VirtualAPK#136]
好像少了`com.didi.virtualapk:gradle`这块的代码，预计什么时候可以开源？

**Comment by dodola** [comment]
@zacklpx 你可以先看看dev分支里的[https://github.com/didi/VirtualAPK/tree/dev/virtualapk-gradle-plugin](url)

**Comment by zhengtao620** [comment]
dev分支，virtualapk-gradle-plugin目录下。@dodola 提供的url404。

**Comment by singwhatiwanna** [comment]
@zacklpx 已经开源了。
