### ISSUE TITLE
gradle插件版本较低。

### ISSUE THREAD

**Issue by easternHong** [didi/VirtualAPK#139]
`Error:(2, 0) Unable to load class 'com.android.builder.dependency.LibraryDependency'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.`

**Comment by Lee-swifter** [comment]
我也碰到了这个问题，目前看到的只要在插件工程中加入 `apply plugin: 'com.didi.virtualapk.plugin'`就会出现这个问题，就算是用 gradle wrapper 也会有。（ virtualApk 中的3个参数也都正确配置了）

**Comment by Res2013** [comment]
同碰到这个问题

**Comment by easternHong** [comment]
1.可见大厂追求的是稳定，不能随便更新lib版本。
2.开源支持的力度不够。

**Comment by XiuLin** [comment]
请使用最新dev分支构建。
