### ISSUE TITLE
Android8.0上兼容性问题

### ISSUE THREAD

**Issue by ljzjohnliu** [didi/VirtualAPK#144]
在hookSystemServices时候，如下反射形式获取变量gDefault
Singleton<IActivityManager> defaultSingleton = (Singleton<IActivityManager>) ReflectUtil.getField(ActivityManagerNative.class, null, "gDefault");

该变量在Android8.0上是不存在的，请大牛支持下

**Comment by singwhatiwanna** [comment]
早就已经支持了呀
