### ISSUE TITLE
Android Studio 3.0打包插件出现乱码

### ISSUE THREAD

**Issue by pengjianbo** [didi/VirtualAPK#147]
使用as3.0打包插件，然后host启动插件后插件上的所有中文都变成乱码，包括toast/activity/logs。主程序正常。

换成as 2.3.3没有该问题

**Comment by XiuLin** [comment]
构建过程不依赖IDE版本，请您看看是否使用正确的构建过程所依赖的gradle版本。

**Comment by pengjianbo** [comment]
我怀疑是AS 3.0打包生成的apk与AS3.0之前的版本生成的apk有差异（因为AS3.0打包出来的APK是不能直接修改扩展名为*.zip然后解压的。我使用的是OSX不能直接解压）之前的版的AS没问题。已验证
