### ISSUE TITLE
只能用Gradle 2.14.1吗？

### ISSUE THREAD

**Issue by young4979** [didi/VirtualAPK#148]
使用Gradle 3.3编译插件module报错 切换到2.14.1后编译成功

Error:(36, 0) Unable to load class 'com.android.builder.dependency.LibraryDependency'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by XiuLin** [comment]
是的 只能依赖 gradle 2.14.1

**Comment by XiuLin** [comment]
请使用dev分支
