### ISSUE TITLE
提供的demo运行起来就崩溃了

### ISSUE THREAD

**Issue by hljstardust** [didi/VirtualAPK#152]
$ ./gradlew clean assemblePlugin
Incremental java compilation is an incubating feature.

**Comment by hljstardust** [comment]
$ ./gradlew clean assemblePlugin
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> character to be escaped is missing

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.481 secs

**Comment by oneapp1e** [comment]
我也遇到了，不知道解决了没有啊

**Comment by XiuLin** [comment]
看看是不是JDK版本不对，需要是1.8的
