### ISSUE TITLE
android studio3.0下gradle出错

### ISSUE THREAD

**Issue by jingzhanwu** [didi/VirtualAPK#153]
我的android studio3.0，gradle是4.1，gradle中添加apply plugin: 'com.didi.virtualapk.host' 这句编译时出现如下错误：
Could not get unknown property 'textSymbolOutputDir' for task ':app:processDebugResources' of type com.android.build.gradle.tasks.ProcessAndroidResources.
不支持androuid studio3.0还是什么原因

**Comment by XiuLin** [comment]
按照官方要求，使用相关gradle版本，如果是windows使用dev分支

**Comment by Effective-Xy** [comment]
请问什么时候才能支持gradle 4.1呢，项目里用到了google()仓库，必须要求gradle版本在4.1以上

**Comment by shenpeibao** [comment]
？？？

**Comment by LZHS** [comment]
我也遇到了这个问题。Could not get unknown property 'textSymbolOutputDir' for task ':app:processDebugResources' of type com.android.build.gradle.tasks.ProcessAndroidResources.

**Comment by jamin918** [comment]
我的是windows环境下，android studio3.0，gradle是4.1，也出现这个问题，做了下面的修改问题解决了：
project下的build.gradle:
`buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
//        classpath 'com.android.tools.build:gradle:3.0.0'

        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.didi.virtualapk:gradle:0.9.4'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

app下的build.gradle:
`apply plugin: 'com.android.application'
apply plugin: 'com.didi.virtualapk.host'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.3'
    defaultConfig {
        applicationId "jamin.study.virtualapktest"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    /*implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'*/

    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.4.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test:runner:1.0.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'com.didi.virtualapk:core:0.9.1'
}`

**Comment by LZHS** [comment]
是的，，问题出在
`implementation 'com.android.support:appcompat-v7:26.1.0'
implementation 'com.android.support.constraint:constraint-layout:1.0.2'
testImplementation 'junit:junit:4.12'
androidTestImplementation 'com.android.support.test🏃1.0.1'
androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'`  

把它改成`
compile 'com.android.support:appcompat-v7:25.4.0'
compile 'com.android.support.constraint:constraint-layout:1.0.2'
testCompile 'junit:junit:4.12'
androidTestCompile 'com.android.support.test:runner:1.0.1'
androidTestCompile 'com.android.support.test.espresso:espresso-core:3.0.1'`  

这样问题就没问题啦
