### ISSUE TITLE
业务项目集成后启动插件报错ActivityNotFound...have you declared this activity ..  空demo正常

### ISSUE THREAD

**Issue by Mars212** [didi/VirtualAPK#154]
1 用官方demo的 host 和plugin程序  正常
2 自己new一个新host工程  打开 官方plugin  正常
3 将现有的一个比较大的项目集成为host  打开官方plugin  报上述错误   说plugin里的acitivity没注册   

是否是因为和一些第三方库冲突的导致的  butterknife? 听云？    还是其他原因导致的   ？

**Comment by hprostudy** [comment]
@Mars212 请问在Window下使用官方demo（0.9.0），assemblePlugin成功后加载插件也报这个错误是什么情况？

**Comment by Mars212** [comment]
官方demo我没有出现这个问题。。可能是哪个配置的细节导致的吧？建立还是新建一个工程来当host   试试

**Comment by zuoanguo** [comment]
加载空的插件，就可以，加载一个比较大的插件 好像有问题，你解决了吗？

**Comment by zuoanguo** [comment]
@Mars212    @hprostudy   我跟你是通用的情况（我自建的项目），插件gradle  assemblePlugin成功了，但提示找不到activity,请问你解决了吗？

**Comment by hprostudy** [comment]
没有。  我在Mac上编译，没问题了。。。

**Comment by XiuLin** [comment]
你看看 是不是gradle配置有问题。按照官方demo进行配置，如有问题请到官方交流群中提出。

**Comment by helloworkcupid** [comment]
我的情况和1楼类似，我是集成了很多封装的东西，这样就提示插件未注册！
