### ISSUE TITLE
apply plugin: 'com.didi.virtualapk.plugin' 报错

### ISSUE THREAD

**Issue by nadyboy** [didi/VirtualAPK#157]
Unable to load class 'com.android.builder.dependency.LibraryDependency'. Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.) Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem. Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by Mars212** [comment]
应该是你项目里面用的第三方库对gradletool版本要求高 比如  greendao3.2

**Comment by XiuLin** [comment]
请按照官方要求的gradle版本进行构建
