### ISSUE TITLE
资源不兼容吗？请问这个谁遇到过，怎么解决？

### ISSUE THREAD

**Issue by helloworkcupid** [didi/VirtualAPK#159]
:tuyaTest:compileReleaseJavaWithJavac
:tuyaTest:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2681: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] AnimatedVectorDrawable = { null };
                                                             ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2683: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] AnimatedVectorDrawableTarget = { null, null };
                                                                   ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2683: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] AnimatedVectorDrawableTarget = { null, null };
                                                                         ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                               ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                                     ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                                           ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                                                 ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                                                       ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                                                             ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2686: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] Animator = { null, null, null, null, null, null, null, 0x6e0100bd };
                                                                                   ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2913: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] HorizontalListView = { null, null, null, 0x6e010043 };
                                                         ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2913: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] HorizontalListView = { null, null, null, 0x6e010043 };
                                                               ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2913: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] HorizontalListView = { null, null, null, 0x6e010043 };
                                                                     ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:2971: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] MorphButton = { null, 0x6e0100af, 0x6e0100a9, 0x6e0100a6, 0x6e0100a7, 0x6e0100a8, 0x6e0100ac, 0x6e0100ad };
                                                  ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:3028: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] PropertyAnimator = { null, 0x6e0100ae };
                                                       ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:3031: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] RoundedImageView = { null, 0x6e01008b, 0x6e01008a, 0x6e010089, 0x6e01008c, 0x6e01008d };
                                                       ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:3150: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] VectorDrawable = { null, null, null, null, 0x6e0100a5, 0x6e0100b6, 0x6e0100b7, 0x6e0100bf, 0x6e0100be };
                                                     ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:3150: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] VectorDrawable = { null, null, null, null, 0x6e0100a5, 0x6e0100b6, 0x6e0100b7, 0x6e0100bf, 0x6e0100be };
                                                           ^
E:\TestDemo\tuyasmart_android\tuyaTest\build\generated\source\r\release\com\tuya\smart\android\myapk\R.java:3150: 错误: 不兼容的类型: <空值>无法转换为int

**Comment by XiuLin** [comment]
最好在交流群中提出相关有问题的demo，精简一下尽量只包含有问题的资源和代码。

**Comment by helloing6** [comment]
我也遇到了，怎么版
