### ISSUE TITLE
Could not find com.didi.foundation:sdk:1.2.0

### ISSUE THREAD

**Issue by caokunhk** [didi/VirtualAPK#16]
D:\download\VirtualAPK-master>gradlew clean iR
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.didi.foundation:sdk:1.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.pom
         https://repo1.maven.org/maven2/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.jar
         https://jcenter.bintray.com/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.pom
         https://jcenter.bintray.com/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.jar
         file:/D:/as/Android/sdk/extras/android/m2repository/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.pom
         file:/D:/as/Android/sdk/extras/android/m2repository/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.jar
         file:/D:/as/Android/sdk/extras/google/m2repository/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.pom
         file:/D:/as/Android/sdk/extras/google/m2repository/com/didi/foundation/sdk/1.2.0/sdk-1.2.0.jar

**Comment by chenenyu** [comment]
demo里面是没有引用这个lib的吧？

**Comment by singwhatiwanna** [comment]
@caokunhk 那个是个例子，并不存在那个aar，请换成自己的aar。
