### ISSUE TITLE
加载插件后提示have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by hprostudy** [didi/VirtualAPK#160]
请问在window是电脑按照wiki编译插件后，加载是报错（版本：0.9.0）。  Mac下可以正常运行
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@75496af
12-07 14:54:57.512 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message start: fd=45,tag =0X01004801
12-07 14:54:57.513 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message copy: fd=45,msgid =913,len=78,msg={"activity":"com.didi.virtualapk/com.didi.virtualapk.MainActivity","frames":2}
12-07 14:54:57.513 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message stop: fd =45,msgid =913
12-07 14:55:09.089 26218-26226/com.didi.virtualapk I/art: Debugger is active
12-07 14:55:09.201 26218-26226/com.didi.virtualapk I/art: Starting a blocking GC Instrumentation
12-07 14:55:10.613 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message start: fd=45,tag =0X01004801
12-07 14:55:10.613 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message copy: fd=45,msgid =921,len=78,msg={"activity":"com.didi.virtualapk/com.didi.virtualapk.MainActivity","frames":1}
12-07 14:55:10.613 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message stop: fd =45,msgid =921
12-07 14:55:18.272 26218-26218/com.didi.virtualapk V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2b3b459
12-07 14:55:18.273 26218-26218/com.didi.virtualapk V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d4d181e
12-07 14:55:18.349 26218-26218/com.didi.virtualapk D/ryg: onCreate cpu arch is arm64-v8a
12-07 14:55:22.604 26218-26218/com.didi.virtualapk D/MyApplication: application start, process name:com.didi.virtualapk
12-07 14:55:27.020 26218-26218/com.didi.virtualapk D/ryg: onCreate classloader is dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.didi.virtualapk-2/base.apk", zip file "/storage/emulated/0/Test.apk"],nativeLibraryDirectories=[/data/app/com.didi.virtualapk-2/lib/arm, /system/fake-libs, /data/app/com.didi.virtualapk-2/base.apk!/lib/armeabi-v7a, /data/user/0/com.didi.virtualapk/app_valibs, /system/lib, /vendor/lib]]]
12-07 14:55:27.160 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message start: fd=45,tag =0X01004801
12-07 14:55:27.160 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message copy: fd=45,msgid =934,len=78,msg={"activity":"com.didi.virtualapk/com.didi.virtualapk.MainActivity","frames":4}
12-07 14:55:27.160 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message stop: fd =45,msgid =934
12-07 14:55:27.212 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message start: fd=45,tag =0X01004801
12-07 14:55:27.212 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message copy: fd=45,msgid =936,len=78,msg={"activity":"com.didi.virtualapk/com.didi.virtualapk.MainActivity","frames":1}
12-07 14:55:27.212 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message stop: fd =45,msgid =936
12-07 14:55:32.352 26218-26218/com.didi.virtualapk V/PerformanceManager: mNotifyFunc method = public int com.zeusis.hawkeye.PerformanceManager.notify(int)
12-07 14:55:32.353 26218-26218/com.didi.virtualapk W/PerformanceManager: ##### open,mFd=57
12-07 14:55:32.353 26218-26218/com.didi.virtualapk V/PerformanceManager_JNI: event notify: fd = 57, event_id = 0X00304802
12-07 14:55:32.356 26218-26218/com.didi.virtualapk I/VAInstrumentation: execStartActivity[com.didi.virtualapk : com.didi.virtualapk.demo.aidl.BookManagerActivity]
12-07 14:55:32.361 26218-26218/com.didi.virtualapk W/System.err: java.lang.reflect.InvocationTargetException
12-07 14:55:32.362 26218-26218/com.didi.virtualapk W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-07 14:55:32.363 26218-26218/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.utils.ReflectUtil.invoke(ReflectUtil.java:86)
12-07 14:55:32.363 26218-26218/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.internal.VAInstrumentation.realExecStartActivity(VAInstrumentation.java:80)
12-07 14:55:32.364 26218-26218/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.internal.VAInstrumentation.execStartActivity(VAInstrumentation.java:66)
12-07 14:55:32.365 26218-26218/com.didi.virtualapk W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4368)
12-07 14:55:32.365 26218-26218/com.didi.virtualapk W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4326)
12-07 14:55:32.366 26218-26218/com.didi.virtualapk W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
12-07 14:55:32.366 26218-26218/com.didi.virtualapk W/System.err:     at android.app.Activity.startActivity(Activity.java:4668)
12-07 14:55:32.367 26218-26218/com.didi.virtualapk W/System.err:     at android.app.Activity.startActivity(Activity.java:4633)
12-07 14:55:32.367 26218-26218/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.MainActivity.onButtonClick(MainActivity.java:53)
12-07 14:55:32.368 26218-26218/com.didi.virtualapk W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-07 14:55:32.368 26218-26218/com.didi.virtualapk W/System.err:     at android.view.View$DeclaredOnClickListener.onClick(View.java:4997)
12-07 14:55:32.369 26218-26218/com.didi.virtualapk W/System.err:     at android.view.View.performClick(View.java:5914)
12-07 14:55:32.370 26218-26218/com.didi.virtualapk W/System.err:     at android.view.View$PerformClick.run(View.java:22953)
12-07 14:55:32.370 26218-26218/com.didi.virtualapk W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
12-07 14:55:32.371 26218-26218/com.didi.virtualapk W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-07 14:55:32.371 26218-26218/com.didi.virtualapk W/System.err:     at android.os.Looper.loop(Looper.java:154)
12-07 14:55:32.372 26218-26218/com.didi.virtualapk W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6217)
12-07 14:55:32.372 26218-26218/com.didi.virtualapk W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-07 14:55:32.373 26218-26218/com.didi.virtualapk W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:929)
12-07 14:55:32.373 26218-26218/com.didi.virtualapk W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819)
12-07 14:55:32.375 26218-26218/com.didi.virtualapk W/System.err: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.didi.virtualapk/com.didi.virtualapk.demo.aidl.BookManagerActivity}; have you declared this activity in your AndroidManifest.xml?
12-07 14:55:32.375 26218-26218/com.didi.virtualapk W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1821)
12-07 14:55:32.375 26218-26218/com.didi.virtualapk W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
12-07 14:55:32.376 26218-26218/com.didi.virtualapk W/System.err: 	... 21 more
12-07 14:55:32.376 26218-26218/com.didi.virtualapk V/PerformanceManager_JNI: event notify: fd = 57, event_id = 0X00304803
12-07 14:55:32.601 26218-26218/com.didi.virtualapk D/ryg: query book:3, Android
12-07 14:55:32.601 26218-26218/com.didi.virtualapk D/ryg: query book:4, Ios
12-07 14:55:32.601 26218-26218/com.didi.virtualapk D/ryg: query book:5, Html5
12-07 14:55:32.607 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message start: fd=45,tag =0X01004801
12-07 14:55:32.607 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message copy: fd=45,msgid =937,len=80,msg={"activity":"com.didi.virtualapk/com.didi.virtualapk.MainActivity","frames":217}
12-07 14:55:32.607 26218-26218/com.didi.virtualapk V/BugManager_JNI: bug message stop: fd =45,msgid =937
12-07 14:55:32.608 26218-26218/com.didi.virtualapk I/Choreographer: Skipped 217 frames!  The application may be doing too much work on its main thread.

**Comment by XiuLin** [comment]
windows请使用dev分支进行测试，开发

**Comment by helloworkcupid** [comment]
请问解决了吗？
