### ISSUE TITLE
一个xml文件导致的错误 : 不兼容的类型: <空值>无法转换为int

### ISSUE THREAD

**Issue by helloworkcupid** [didi/VirtualAPK#161]
- :app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
E:\study\VirtualAPK\VirtualAPK-dev\PluginDemo\app\build\generated\source\r\release\com\didi\virtualapk\demo\R.java:1618: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] HorizontalListView = { null, null, null, 0x6f010043 };
                                                         ^
E:\study\VirtualAPK\VirtualAPK-dev\PluginDemo\app\build\generated\source\r\release\com\didi\virtualapk\demo\R.java:1618: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] HorizontalListView = { null, null, null, 0x6f010043 };
                                                               ^
E:\study\VirtualAPK\VirtualAPK-dev\PluginDemo\app\build\generated\source\r\release\com\didi\virtualapk\demo\R.java:1618: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] HorizontalListView = { null, null, null, 0x6f010043 };
                                                                     ^
E:\study\VirtualAPK\VirtualAPK-dev\PluginDemo\app\build\generated\source\r\release\com\didi\virtualapk\demo\R.java:1736: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] RoundedImageView = { null, 0x6f01008a, 0x6f010089, 0x6f010088, 0x6f01008b, 0x6f01008c };
                                                       ^
4 个错误

- [ ] 

-xml文件 如下：

<vector xmlns:android="http://schemas.android.com/apk/res/android"
    
    <path
        app:vc_fillColor="#FF000000"
        app:vc_pathData="M36,56m-2,0a2,2 0,1 1,4 0a2,2 0,1 1,-4 0"/>

    <path
        android:fillColor="#FF000000"
        android:pathData="M36,40.5c-5.8,0 -11.4,4.5 -11.6,4.7c-0.4,0.3 -0.5,1 -0.1,1.4c0.3,0.4 1,0.5 1.4,0.1c0.1,0 5.3,-4.3 10.4,-4.3s10.3,4.2 10.4,4.3c0.2,0.2 0.4,0.2 0.6,0.2c0.3,0 0.6,-0.1 0.8,-0.4c0.3,-0.4 0.3,-1.1 -0.1,-1.4C47.4,45 41.8,40.5 36,40.5z"/>
    <path
        android:fillColor="#FF000000"
        android:pathData="M36,27c-10.3,0 -19.3,7.9 -19.7,8.3c-0.4,0.4 -0.4,1 -0.1,1.4c0.4,0.4 1,0.5 1.4,0.1C17.8,36.7 26.5,29 36,29s18.2,7.7 18.3,7.7c0.2,0.2 0.4,0.3 0.7,0.3c0.3,0 0.6,-0.1 0.7,-0.3c0.4,-0.4 0.3,-1 -0.1,-1.4C55.3,34.9 46.3,27 36,27z"/>
    <path
        android:fillColor="#FF000000"
        android:pathData="M63.7,25.2C63.2,24.8 51.7,15 36,15C20.3,15 9.8,24.9 9.3,25.3c-0.4,0.4 -0.4,1 0,1.4c0.4,0.4 1,0.4 1.4,0C10.8,26.6 21.1,17 36,17c14.9,0 26.2,9.7 26.3,9.8c0.2,0.2 0.4,0.2 0.7,0.2c0.3,0 0.6,-0.1 0.8,-0.3C64.1,26.2 64.1,25.6 63.7,25.2z"/>

</vector>

**Comment by helloworkcupid** [comment]
`这个是文件：
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:width="72dp"
    android:height="72dp"
    android:viewportWidth="72.0"
    android:viewportHeight="72.0"
    app:vc_viewportHeight="72.0"
    app:vc_viewportWidth="72.0">
    <path
        app:vc_fillColor="#FF000000"
        app:vc_pathData="M36,56m-2,0a2,2 0,1 1,4 0a2,2 0,1 1,-4 0"/>
    <path
        app:vc_fillColor="#FF000000"
        app:vc_pathData="M36,40.5c-5.8,0 -11.4,4.5 -11.6,4.7c-0.4,0.3 -0.5,1 -0.1,1.4c0.3,0.4 1,0.5 1.4,0.1c0.1,0 5.3,-4.3 10.4,-4.3s10.3,4.2 10.4,4.3c0.2,0.2 0.4,0.2 0.6,0.2c0.3,0 0.6,-0.1 0.8,-0.4c0.3,-0.4 0.3,-1.1 -0.1,-1.4C47.4,45 41.8,40.5 36,40.5z"/>
    <path
        app:vc_fillColor="#FF000000"
        app:vc_pathData="M36,27c-10.3,0 -19.3,7.9 -19.7,8.3c-0.4,0.4 -0.4,1 -0.1,1.4c0.4,0.4 1,0.5 1.4,0.1C17.8,36.7 26.5,29 36,29s18.2,7.7 18.3,7.7c0.2,0.2 0.4,0.3 0.7,0.3c0.3,0 0.6,-0.1 0.7,-0.3c0.4,-0.4 0.3,-1 -0.1,-1.4C55.3,34.9 46.3,27 36,27z"/>
    <path
        app:vc_fillColor="#FF000000"
        app:vc_pathData="M63.7,25.2C63.2,24.8 51.7,15 36,15C20.3,15 9.8,24.9 9.3,25.3c-0.4,0.4 -0.4,1 0,1.4c0.4,0.4 1,0.4 1.4,0C10.8,26.6 21.1,17 36,17c14.9,0 26.2,9.7 26.3,9.8c0.2,0.2 0.4,0.2 0.7,0.2c0.3,0 0.6,-0.1 0.8,-0.3C64.1,26.2 64.1,25.6 63.7,25.2z"/>
    <path
        android:fillColor="#FF000000"
        android:pathData="M36,56m-2,0a2,2 0,1 1,4 0a2,2 0,1 1,-4 0"/>
    <path
        android:fillColor="#FF000000"
        android:pathData="M36,40.5c-5.8,0 -11.4,4.5 -11.6,4.7c-0.4,0.3 -0.5,1 -0.1,1.4c0.3,0.4 1,0.5 1.4,0.1c0.1,0 5.3,-4.3 10.4,-4.3s10.3,4.2 10.4,4.3c0.2,0.2 0.4,0.2 0.6,0.2c0.3,0 0.6,-0.1 0.8,-0.4c0.3,-0.4 0.3,-1.1 -0.1,-1.4C47.4,45 41.8,40.5 36,40.5z"/>
    <path
        android:fillColor="#FF000000"
        android:pathData="M36,27c-10.3,0 -19.3,7.9 -19.7,8.3c-0.4,0.4 -0.4,1 -0.1,1.4c0.4,0.4 1,0.5 1.4,0.1C17.8,36.7 26.5,29 36,29s18.2,7.7 18.3,7.7c0.2,0.2 0.4,0.3 0.7,0.3c0.3,0 0.6,-0.1 0.7,-0.3c0.4,-0.4 0.3,-1 -0.1,-1.4C55.3,34.9 46.3,27 36,27z"/>
    <path
        android:fillColor="#FF000000"
        android:pathData="M63.7,25.2C63.2,24.8 51.7,15 36,15C20.3,15 9.8,24.9 9.3,25.3c-0.4,0.4 -0.4,1 0,1.4c0.4,0.4 1,0.4 1.4,0C10.8,26.6 21.1,17 36,17c14.9,0 26.2,9.7 26.3,9.8c0.2,0.2 0.4,0.2 0.7,0.2c0.3,0 0.6,-0.1 0.8,-0.3C64.1,26.2 64.1,25.6 63.7,25.2z"/>

</vector>

**Comment by XiuLin** [comment]
最好在交流群中提出相关有问题的demo，精简一下尽量只包含有问题的资源和代码。

**Comment by Wanchen7** [comment]
有解决方案吗？ 我也遇到了。

        public static final int[] Theme = { null, null, 0x7f010084, 0x7f010085, 0x7f010086, 0x7f010087, 0x7f010088, 0x7f010089, 0x7f01008a, 0x7f01008b, 0x7f01008c, 0x7f01008d, 0x7f01008e, 0x7f01008f, 0x7f010090, 0x7f010091, 0x7f010092, 0x7f010093, 0x7f010094, 0x7f010095, 0x7f010096, 0x7f010097, 0x7f010098, 0x7f010099, 0x7f01009a, 0x7f01009b, 0x7f01009c, 0x7f01009d, 0x7f01009e, 0x7f01009f, 0x7f0100a0, 0x7f0100a1, 0x7f0100a2, 0x7f0100a3, 0x7f0100a4, 0x7f0100a5, 0x7f0100a6, 0x7f0100a7, 0x7f0100a8, 0x7f0100a9, 0x7f0100aa, 0x7f0100ab, 0x7f0100ad, 0x7f0100ae, 0x7f0100af, 0x7f0100b0, 0x7f0100b1, 0x7f0100b2, 0x7f0100b3, 0x7f0100b4, 0x7f0100b5, 0x7f0100b6, 0x7f0100b7, 0x7f0100b8, 0x7f0100b9, 0x7f0100ba, 0x7f0100bb, 0x7f0100bc, 0x7f0100bd, 0x7f0100be, 0x7f0100bf, 0x7f0100c0, 0x7f0100c1, 0x7f0100c2, 0x7f0100c4, 0x7f0100c5, 0x7f0100c6, 0x7f0100c7, 0x7f0100c8, 0x7f0100c9, 0x7f0100ca, 0x7f0100cb, 0x7f0100cc};

**Comment by helloworkcupid** [comment]
没有解决掉，抽减后，发现问题不存在了，看情况再分析下把，在复杂的项目中会有这样的问题，剥离开，却又不是因为这个xml文件

**Comment by XiuLin** [comment]
注意一下构建时候 依赖的v7版本。选择统一的版本。

**Comment by Korolye** [comment]
这个问题怎么解决啊

**Comment by XiuLin** [comment]
还有就是 buildtools的版本要 看看修改成和demo中的一致
