### ISSUE TITLE
Library Module使用ButterKnife插件和VirtualApk插件时构建出错

### ISSUE THREAD

**Issue by Res2013** [didi/VirtualAPK#165]
插件工程依赖一个Android Library Module，该Library使用ButterKnife插件(apply plugin: 'com.jakewharton.butterknife')的时候，插件工程使用gradlew clean assemblePlugin是会报错的。

    环境为："WIN7 + virtualapk 0.9.4 + gradle tool 2.3.3 + gradle 3.3 + build tools 25.0.1"

**Comment by helloworkcupid** [comment]
这个问题，我以前也遇到过的，还有些其他使用资源文件也会报错

**Comment by Res2013** [comment]
补充一点，开启混淆且使用了apply plugin: 'com.jakewharton.butterknife'才会出现问题！

**Comment by Res2013** [comment]
现在不确定是VirtualAPK Plugin问题，也可能是ButterKnife Plugin问题，先关闭了！
