### ISSUE TITLE
目前是不是没有适配8.0系统

### ISSUE THREAD

**Issue by yanshao** [didi/VirtualAPK#167]
如题

**Comment by 852172891** [comment]
已经适配了，例如 ：PluginManager中
      private void prepare() {
        Systems.sHostContext = getHostContext();
        this.hookInstrumentationAndHandler();
        if (Build.VERSION.SDK_INT >= 26) {
            this.hookAMSForO();
        } else {
            this.hookSystemServices();
        }
    }
