### ISSUE TITLE
LoadedPlugin.getClassLoader() on a null object reference

### ISSUE THREAD

**Issue by SlipperM** [didi/VirtualAPK#168]
描述： app目前启动时加载两个插件，从assets目录下拷贝文件到缓存目录，再进行加载。我们测试时都能加载插件并能正常使用，但线上bugly反馈主要有两个闪退异常，日志如下：

`java.lang.RuntimeException:Unable to instantiate activity ComponentInfo{com.anjiu.guardian.c4227/com.didi.virtualapk.core.C$1}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader com.didi.virtualapk.internal.LoadedPlugin.getClassLoader()' on a null object reference

4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.ClassLoader com.didi.virtualapk.internal.LoadedPlugin.getClassLoader()' on a null object reference
6 com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:105)
7 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2471)
8 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
9 android.app.ActivityThread.-wrap11(ActivityThread.java)
10 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
11 android.os.Handler.dispatchMessage(Handler.java:111)
12 android.os.Looper.loop(Looper.java:207)
13 android.app.ActivityThread.main(ActivityThread.java:5737)
14 java.lang.reflect.Method.invoke(Native Method)
15 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
16 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
`

定位到的代码如下
```
 @Override
    public Activity newActivity(ClassLoader cl, String className, Intent intent) throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        try {
            cl.loadClass(className);
        } catch (ClassNotFoundException e) {
            //plugin为null
            LoadedPlugin plugin = this.mPluginManager.getLoadedPlugin(intent);
            String targetClassName = PluginUtil.getTargetActivity(intent);
            //className和targetClassName都能打印出来
            Log.i(TAG, String.format("newActivity[%s : %s]", className, targetClassName));

            if (targetClassName != null) {
                // TODO: 18/1/11   bugly 反馈 plugin为 null
                Activity activity = mBase.newActivity(plugin.getClassLoader(), targetClassName, intent);
                activity.setIntent(intent);

                try {
                    // for 4.1+
                    ReflectUtil.setField(ContextThemeWrapper.class, activity, "mResources", plugin.getResources());
                } catch (Exception ignored) {
                    // ignored.
                }

                return activity;
            }
        }

        return mBase.newActivity(cl, className, intent);
    }
```

**Comment by XiuLin** [comment]
我建议你把包名也打出来，这么看就是对应的包没有加载。

**Comment by SlipperM** [comment]
包名是有的，也是正确的包名，抓到的日志如下

```
17901-18 11:08:33.122 32306 32306 I VAInstrumentation: newActivity[com.didi.virtualapk.core.C$1 : com.anjiu.pay.PayActivity]
--
18001-18 11:08:33.122 32306 32306 D AndroidRuntime: Shutting down VM
```

而且在跳转到插件的时候都会先判断插件是否已经加载
`mPluginManager.getLoadedPlugin(pkg)`

**Comment by superqiaopu** [comment]
看下intent.toURI() 是什么

**Comment by superqiaopu** [comment]
长时间无回复，关闭。
