### ISSUE TITLE
demo 插件编译不过 as windows环境

### ISSUE THREAD

**Issue by zhenggang510322** [didi/VirtualAPK#173]
F:\demo\loadapk\VirtualAPK-master\PluginDemo\app\build\generated\source\r\beijin
        public static final int[] ColorStateListItem = { null, null, 0x6f010001
                                                         ^
F:\demo\loadapk\VirtualAPK-master\PluginDemo\app\build\generated\source\r\beijin
        public static final int[] ColorStateListItem = { null, null, 0x6f010001
                                                               ^
F:\demo\loadapk\VirtualAPK-master\PluginDemo\app\build\generated\source\r\beijin
        public static final int[] CompoundButton = { null, 0x6f010006, 0x6f01000
                                                     ^
F:\demo\loadapk\VirtualAPK-master\PluginDemo\app\build\generated\source\r\beijin
        public static final int[] ViewBackgroundHelper = { null, 0x7f0100c7, 0x7
                                                           ^
15 个个错错误误
:app:compileBeijingReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileBeijingReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --inf

BUILD FAILED

**Comment by XiuLin** [comment]
windows下使用dev分支，其次看看gradle依赖的一些库。比如    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
删除了试试。或者和宿主一致。
