### ISSUE TITLE
VirtualAPK对Data-Binding的支持

### ISSUE THREAD

**Issue by yandaoqiu** [didi/VirtualAPK#178]
目前Data-Binding接入会出现 空指针异常
![image](https://user-images.githubusercontent.com/8401986/35840370-cde23004-0b30-11e8-9dac-833386edc499.png)

**Comment by XiuLin** [comment]
使用dev分支实验，我验证过并没有发现

**Comment by fcloud89** [comment]
是不是插件里databinding不支持？

**Comment by superqiaopu** [comment]
目前不支持 Data-Binding 框架。

使用该框架会在宿主包和插件包生成固定包名的 android.databinding.DataBinderMapper 类，在运行时通过VirtualAPK的类加载机制只会加载宿主中的类，因此使用DataBindingUtil.setContentView() 等 API 时会返回 null。

由于该框架使用范围较广，未来版本会考虑支持该框架。

**Comment by superqiaopu** [comment]
新版本已支持，请关注dev分支。
