### ISSUE TITLE
ContextImpl单例现象

### ISSUE THREAD

**Issue by ileelay** [didi/VirtualAPK#179]
正常情况下，一个Activity对应一个ContextImpl对象即mBase，然而VirtualAPK插件中的所有Activity和宿主Application共用同一个ContextImpl对象，这样比如我在插件Activity中调用registerReceiver()，代码会走到ContextImpl的registerReceiverInternal()，而该方法参数中的Context来自getOuterContext()，getOuterContext()返回的是宿主Application对象，在ContextImpl中调用getOuterContext()的不止这一处，另外在构造ContextImpl时，有createAppContext()和createActivityContext()之分，传参有细微差别，综上这两点，有点疑惑这样搞会不会有有问题，高手给个指点呗。

**Comment by superqiaopu** [comment]
不返回宿主 Application 对象，如何能正常启动 receiver。研究一下相关的系统源码就知道了。
