### ISSUE TITLE
执行 ./gradlew clean iR报错

### ISSUE THREAD

**Issue by yqyzxd** [didi/VirtualAPK#185]
VirtualAPK-master wind$ ./gradlew clean iR

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/wind/third_library/VirtualAPK-master/AndroidStub/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':AndroidStub'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.828 secs

**Comment by XiuLin** [comment]
请按照官方要求和demo 进行构建
