### ISSUE TITLE
启动另一个未安装但已经配置过的的apk报错

### ISSUE THREAD

**Issue by YuedongMa** [didi/VirtualAPK#188]
刚集成根据步骤写的，在宿主apk中点开另一个apk,报
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.yuedong.library/com.didi.virtualapk.core.A$1}: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x10
	at android.app.ActivityThread.performLaunchActivity
请问是不是哪配置错误了呀

**Comment by XiuLin** [comment]
你看看 你packageID的值设置成什么了？
