### ISSUE TITLE
android9.0限制私有api反射，方案会受影响吗？

### ISSUE THREAD

**Issue by mqzhangw** [didi/VirtualAPK#190]
android9.0限制私有api反射，方案会受影响吗？有兼容方案吗？

**Comment by CarGuo** [comment]
![555](https://user-images.githubusercontent.com/10770362/37580923-31c7cfb4-2b81-11e8-8c3f-9e400724ba50.png)

**Comment by jjlan** [comment]
同问，如果限制了类似于addAssetPath这种核心api，VirtualApk有办法绕过去吗

**Comment by superqiaopu** [comment]
正式版本发布后会进行适配，请关注dev分支。
