### ISSUE TITLE
宿主启动任一插件后，进入宿主中带有WebView的页面，宿主闪退

### ISSUE THREAD

**Issue by CrystalIFDE** [didi/VirtualAPK#191]
若在xml中写WebView，报错如图
![image](https://user-images.githubusercontent.com/18493026/37379765-1dace79a-2770-11e8-9c2f-798e87853867.png)
若在代码中new WebView(context)，报错如图
![image](https://user-images.githubusercontent.com/18493026/37379784-404f46ee-2770-11e8-9490-5e4caed6459a.png)
gradle plugin : 0.9.4
core library : 0.9.1
System Version : Android 6.0,Flyme 5.1.1,Android 5.1.1

**Comment by superqiaopu** [comment]
https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B

**Comment by liuxiaoying** [comment]
我这个问题发生在Android9.0.10.0的手机上面，我的解决方法是宿主在application中初始化的时候调用反射WebView的方法
 public static void hookWebView(){
        int sdkInt = Build.VERSION.SDK_INT;
        try {
            Class<?> factoryClass = Class.forName("android.webkit.WebViewFactory");
            Field field = factoryClass.getDeclaredField("sProviderInstance");
            field.setAccessible(true);
            Object sProviderInstance = field.get(null);
            if (sProviderInstance != null) {
                Log.i(BmBaseConstance.JOKE_TAG,"sProviderInstance isn't null");
                return;
            }

            Method getProviderClassMethod;
            if (sdkInt > 22) {
                getProviderClassMethod = factoryClass.getDeclaredMethod("getProviderClass");
            } else if (sdkInt == 22) {
                getProviderClassMethod = factoryClass.getDeclaredMethod("getFactoryClass");
            } else {
                Log.i(BmBaseConstance.JOKE_TAG,"Don't need to Hook WebView");
                return;
            }
            getProviderClassMethod.setAccessible(true);
            Class<?> factoryProviderClass = (Class<?>) getProviderClassMethod.invoke(factoryClass);
            Class<?> delegateClass = Class.forName("android.webkit.WebViewDelegate");
            Constructor<?> delegateConstructor = delegateClass.getDeclaredConstructor();
            delegateConstructor.setAccessible(true);
            if(sdkInt < 26){//低于Android O版本
                Constructor<?> providerConstructor = factoryProviderClass.getConstructor(delegateClass);
                if (providerConstructor != null) {
                    providerConstructor.setAccessible(true);
                    sProviderInstance = providerConstructor.newInstance(delegateConstructor.newInstance());
                }
            } else {
                Field chromiumMethodName = factoryClass.getDeclaredField("CHROMIUM_WEBVIEW_FACTORY_METHOD");
                chromiumMethodName.setAccessible(true);
                String chromiumMethodNameStr = (String)chromiumMethodName.get(null);
                if (chromiumMethodNameStr == null) {
                    chromiumMethodNameStr = "create";
                }
                Method staticFactory = factoryProviderClass.getMethod(chromiumMethodNameStr, delegateClass);
                if (staticFactory!=null){
                    sProviderInstance = staticFactory.invoke(null, delegateConstructor.newInstance());
                }
            }

            if (sProviderInstance != null){
                field.set("sProviderInstance", sProviderInstance);
                Log.i(BmBaseConstance.JOKE_TAG,"Hook success!");
            } else {
                Log.i(BmBaseConstance.JOKE_TAG,"Hook failed!");
            }
        } catch (Throwable e) {
            Log.w(BmBaseConstance.JOKE_TAG,e);
        }
    }
解决问题
