### ISSUE TITLE
错误: 找不到符号???

### ISSUE THREAD

**Issue by zhangbl** [didi/VirtualAPK#193]
###############################################################:app:javaPreCompileRelease
:app:compileReleaseJavaWithJavac
:app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
F:\android\Test\app\src\main\java\juhua\baolei\com\test\MainActivity.java:13: 错误: 找不到符号
        setContentView(R.layout.activity_test);
                        ^
  符号:   变量 layout
  位置: 类 R
F:\android\Test\app\src\main\java\juhua\baolei\com\test\MainActivity.java:14: 错误: 找不到符号
        findViewById(R.id.button_main2).setOnClickListener(new View.OnClickListener() {
                      ^
  符号:   变量 id
  位置: 类 R
2 个错误
:app:compileReleaseJavaWithJavac FAILED

build 插件的时候 出现这个错误，哪位大神知道这是什么原因呀？

**Comment by mqy1023** [comment]
求问怎么解决的？我clean后重新gradlew clean assemblePlugin还是会出现这个问题，单独运行plugin插件app可以运行
