### ISSUE TITLE
错误: 不兼容的类型: <空值>无法转换为int

### ISSUE THREAD

**Issue by JAYAndroid** [didi/VirtualAPK#200]
grade clean assemblePlugin执行后，编译报错
ource/r/release/android/support/constraint/R.java:67: 错误: 不兼容的类型: <空值>无法转换为int
        public static final int[] ConstraintLayout_Layout = { null, null, null, null, null, 0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003, 0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007, 0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b, 0x7f01000c, 0x7f01000d, 0x7f01000e, 0x7f01000f, 0x7f010010, 0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014, 0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018, 0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f01001c, 0x7f01001d, 0x7f01001e, 0x7f01001f, 0x7f010020, 0x7f010021, 0x7f010022, 0x7f010023, 0x7f010024, 0x7f010025, 0x7f010026, 0x7f010027, 0x7f010028, 0x7f010029, 0x7f01002a, 0x7f01002b };

**Comment by flutowoo** [comment]
Hi.

Thank you for your replay.
i'll try clean project.

thanks.

2018-04-08 17:45 GMT+09:00 JAYAndroid <notifications@github.com>:

**Comment by superqiaopu** [comment]
使用更新的版本构建。
