### ISSUE TITLE
同名的资源文件会被覆盖吗

### ISSUE THREAD

**Issue by lyright** [didi/VirtualAPK#204]
运行了一下demo，发现插件里的layout_main被宿主的layout_main覆盖了？插件apk里这个资源不见了

**Comment by helloing6** [comment]
只有问的没有答的，这说明滴滴的工程师还是大多数在工作，不是热爱

**Comment by yunnywu** [comment]
如何插件资源和host资源名称相同，插件内的资源编译时会被删除

**Comment by superqiaopu** [comment]
@helloing6 开源社区的建设需要大家的共同努力，有时间吐槽，不如去阅读源码。欢迎提交PR，那时我敬你是条汉子。

Talk is cheap. Show me the code.
