### ISSUE TITLE
AndroidManifest.xml (系统找不到指定的路径)

### ISSUE THREAD

**Issue by yoyiyi** [didi/VirtualAPK#206]
问题是这样：有主工程A，插件工程B，公共库工程CommonLibrary（CommonLibrary里面有一个module叫common，没有app），插件工程B引用公共库工程里面的common，然后使用gradle 打包插件工程就会报错找不到CommonLibrary里面common的AndroidManifast.xml。必须把common这个module放到B工程里面才能打包插件工程。直接运行，打包运行都问题。
```
CommonLibrary\common\build\intermediates\intermediate-jars\release\full.jar\AndroidManifest.xml (系统找不到指定的路径。)
```
这种公共module是否必须都要放在插件工程里面。

**Comment by helloing6** [comment]
解决了没有？

**Comment by superqiaopu** [comment]
插件的bug，暂时请导出aar依赖。

**Comment by superqiaopu** [comment]
com.didi.virtualapk:gradle:0.9.8.4-dev 已修复。
