### ISSUE TITLE
插件报java.lang.NoClassDefFoundError问题

### ISSUE THREAD

**Issue by helloing6** [didi/VirtualAPK#213]
我的插件，里面有很多的依赖库，独立运行时候没有问题，但是当变成插件后，很多的依赖库中的类都无法找到，报 java.lang.NoClassDefFoundError 异常，请问是什么问题？有好的解决方式吗？

**Comment by helloing6** [comment]
跟android的版本有关系，因为分包机制，5.0之前后之后的机制好像不同

**Comment by superqiaopu** [comment]
请查看相关Wiki：
 [Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
[常见问题解答(不定时更新)](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)

**Comment by YoungBill** [comment]
哥们，这个问题你解决了吗

**Comment by Hujunjob** [comment]
我也是这个问题，特别是我debug时宿主和插件都正常，但是一旦release，就在插件里报错NoClassDefFoundError
