### ISSUE TITLE
com.android.support:design:25.4.0 不可以在插件中继续使用

### ISSUE THREAD

**Issue by helloing6** [didi/VirtualAPK#215]

**Comment by superqiaopu** [comment]
请先查看相关Wiki：
 [Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
[常见问题解答(不定时更新)](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
