### ISSUE TITLE
> Can't find D:\doc\workspace\yw\test\app\build\VAHost\Host_R.txt, please check up your host application     need apply com.didi.virtualapk.host in build.gradle of host application

### ISSUE THREAD

**Issue by Luckflower** [didi/VirtualAPK#220]
你好，
我先编译的宿主，并且编译成功，但是在build下面没有编译生成VAHost文件夹以及下面的文件；
当编译插件apk的时候就出现以下错误，我检查了各种配置，似乎没有问题
> Can't find D:\doc\workspace\yw\test\app\build\VAHost\Host_R.txt, please check up your host application     need apply com.didi.virtualapk.host in build.gradle of host application

**Comment by superqiaopu** [comment]
官方demo能运行成功吗？如果运行成功，参考一下demo中的配置，对比一下有什么区别。

请先查看相关Wiki：
 [Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
[常见问题解答(不定时更新)](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)

**Comment by Luckflower** [comment]
非常感谢你的帮助

**Comment by lhxx225** [comment]
> 你好，
> 我先编译的宿主，并且编译成功，但是在build下面没有编译生成VAHost文件夹以及下面的文件；
> 当编译插件apk的时候就出现以下错误，我检查了各种配置，似乎没有问题
> 
> > Can't find D:\doc\workspace\yw\test\app\build\VAHost\Host_R.txt, please check up your host application     need apply com.didi.virtualapk.host in build.gradle of host application
请问你是怎么弄好的？我也出现了相同的问题
