### ISSUE TITLE
升级到3.0后，对插件进行打包过程出现错误

### ISSUE THREAD

**Issue by helloworkcupid** [didi/VirtualAPK#222]
错误信息：
[INFO][ProcessResourcesHooker] Updated R.java: E:\AndroidProject\Money\app\build\generated\source\r\release\com\sg\zhui\money\R.java
[INFO][ProcessResourcesHooker] Updated R.java: E:\AndroidProject\Money\app\build\intermediates\virtualapk\release\source\r\com\sg\zhui\money\R.java

FAILURE: Build failed with an exception.

* What went wrong:
java.io.FileNotFoundException: E:\AndroidProject\Money\MoneyProject\build\intermediates\intermediate-jars\release\full.jar\AndroidManifest.xml (系统找不到指定的路径。)
> E:\AndroidProject\Money\MoneyProject\build\intermediates\intermediate-jars\release\full.jar\AndroidManifest.xml (系统找不到指定的路径。)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: E:\AndroidProject\Money\MoneyProject\build\intermediates\intermediate-jars\release\full.jar\AndroidManifest.xml (系统找不到指定的路径。)

环境： windows10(家庭版)
 classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.didi.virtualapk:gradle:0.9.8.3'
compile 'com.didi.virtualapk:core:0.9.5' // 代替CoreLibrary

测试手机：小米note3,oppo R7 ，都出现同样的问题

请给予解答，感谢！

**Comment by superqiaopu** [comment]
已知问题，尝鲜版已修复。请使用com.didi.virtualapk:gradle:0.9.8.4.4-dev或更高版本。

**Comment by 1022-zhang** [comment]
请问这个问题怎么避免一下？
