### ISSUE TITLE
按照正常流程集成，AS3.1出现错误No signature of method

### ISSUE THREAD

**Issue by spianmo** [didi/VirtualAPK#224]
No signature of method: static com.android.build.gradle.internal.ide.ArtifactDependencyGraph.getAllArtifacts() is applicable for argument types: (com.android.build.gradle.internal.scope.VariantScopeImpl, com.android.build.gradle.internal.publishing.AndroidArtifacts$ConsumedConfigType, null) values: [VariantScopeImpl{debug}, COMPILE_CLASSPATH, null]
Possible solutions: getAllArtifacts(com.android.build.gradle.internal.scope.VariantScope, com.android.build.gradle.internal.publishing.AndroidArtifacts$ConsumedConfigType, com.android.build.gradle.internal.ide.DependencyFailureHandler, com.google.common.collect.ImmutableMap)

**Comment by 24Lathiya** [comment]
@spianmo  i got same issue. did you get any solution ?

**Comment by 652028815** [comment]
是不是gradle verseion 不支持4.4的？什么时候能更新呢？

**Comment by magiclonw** [comment]
按wiki中的gradle version

**Comment by 5peak2me** [comment]
- 经过查看源码，3.1.3版本`ArtifactDependencyGraph.getAllArtifacts()`新增了一个参数

```
/**
 * Returns a set of HashableResolvedArtifactResult where the {@link
 * HashableResolvedArtifactResult#getDependencyType()} and {@link
 * HashableResolvedArtifactResult#isWrappedModule()} fields have been setup properly.
 *
 * @param variantScope the variant to get the artifacts from
 * @param consumedConfigType the type of the dependency to resolve (compile vs runtime)
 * @param dependencyFailureHandler handler for dependency resolution errors
 * @param buildMapping a build mapping from build name to root dir.
 */
 public static Set<HashableResolvedArtifactResult> getAllArtifacts(
      @NonNull VariantScope variantScope,
      @NonNull AndroidArtifacts.ConsumedConfigType consumedConfigType,
      @Nullable DependencyFailureHandler dependencyFailureHandler,
      @NonNull ImmutableMap<String, String> buildMapping) {
 }
```
项目中3.0.1版本方法为
```
/**
 * Returns a set of HashableResolvedArtifactResult where the {@link
 * HashableResolvedArtifactResult#getDependencyType()} and {@link
 * HashableResolvedArtifactResult#isWrappedModule()} fields have been setup properly.
 */
 public static Set<HashableResolvedArtifactResult> getAllArtifacts(
      @NonNull VariantScope variantScope,
      @NonNull AndroidArtifacts.ConsumedConfigType consumedConfigType,
      @Nullable DependencyFailureHandler dependencyFailureHandler) {
 }
```
可以看到新增了一个ImmutableMap参数，还是非空的，而这个ImmutableMap又是个抽象类
- 而且，修改之后，又发现3.1.3版本去除了`com.android.build.gradle.internal.TaskContainerAdaptor`这个类，它是TaskFactory接口的实现类。
- 同样的 `com.android.builder.core.VariantConfiguration`这个类也去除了
- **gradle版本不断更改，这适配工作也是一个坑！！！**

**Comment by superqiaopu** [comment]
Please use com.didi.virtualapk:gradle:0.9.8.5-dev or the later version.
