### ISSUE TITLE
execution failed for task ' compiledebugjavawithjavac'

### ISSUE THREAD

**Issue by 24Lathiya** [didi/VirtualAPK#225]
Error:Note: E:\WorkSpace\VirtualAPK-master\app\src\main\java\com\didi\virtualapk\MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> No signature of method: static com.android.build.gradle.internal.ide.ArtifactDependencyGraph.getAllArtifacts() is applicable for argument types: (com.android.build.gradle.internal.scope.VariantScopeImpl, com.android.build.gradle.internal.publishing.AndroidArtifacts$ConsumedConfigType, null) values: [VariantScopeImpl{debug}, COMPILE_CLASSPATH, null]
  Possible solutions: getAllArtifacts(com.android.build.gradle.internal.scope.VariantScope, com.android.build.gradle.internal.publishing.AndroidArtifacts$ConsumedConfigType, com.android.build.gradle.internal.ide.DependencyFailureHandler, com.google.common.collect.ImmutableMap)

I did not get how to fix this issue. please let me know how to solve it.  
Thanks in advance.

**Comment by superqiaopu** [comment]
Please use com.didi.virtualapk:gradle:0.9.8.5-dev or the later version.
