### ISSUE TITLE
加固后，不能正常运行。

### ISSUE THREAD

**Issue by jingle729** [didi/VirtualAPK#226]
加固方式：邦邦
宿主包加固后，正常安装可以运行，切可以加载运行无加固的插件包。但是插件包同样方式加固后，只能载入，不能运行。

如何保证宿主包以及插件包的安全呢？

**Comment by jingle729** [comment]
W/System.err(14101): java.lang.ClassNotFoundException: com.didi.virtualapk.demo.provider.BookProvider
W/System.err(14101):    at java.lang.Class.classForName(Native Method)
W/System.err(14101):    at java.lang.Class.forName(Class.java:251)
W/System.err(14101):    at java.lang.Class.forName(Class.java:216)
W/System.err(14101):    at com.didi.virtualapk.delegate.RemoteContentProvider$1.run(RemoteContentProvider.java:90)
W/System.err(14101):    at com.didi.virtualapk.a.e$a.handleMessage(RunUtil.java:122)
W/System.err(14101):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(14101):    at android.os.Looper.loop(Looper.java:136)
W/System.err(14101):    at android.app.ActivityThread.main(ActivityThread.java:5019)
W/System.err(14101):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(14101):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(14101):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err(14101):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err(14101):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(14101): Caused by: java.lang.NoClassDefFoundError: com/didi/virtualapk/demo/provider/BookProvider
W/System.err(14101):    ... 13 more
W/System.err(14101): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.didi.virtualapk.demo.provider.BookProvider" on path: DexPathList[[dex file "dalvik.system.DexFile@4a79448c", zip file "/data/app/com.didi.virtualapk-1.apk", zip file "/storage/emulated/0/app-shanghai-release.apk"],nativeLibraryDirectories=[/data/app-lib/com.did
i.virtualapk-1, /system/lib, /data/user/0/com.didi.virtualapk/app_valibs]]
W/System.err(14101):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err(14101):    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
W/System.err(14101):    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
W/System.err(14101):    ... 13 more
D/AndroidRuntime(14079): Shutting down VM
W/dalvikvm(14079): threadid=1: thread exiting with uncaught exception (group=0x94c4cb20)
E/AndroidRuntime(14079): FATAL EXCEPTION: main
E/AndroidRuntime(14079): Process: com.didi.virtualapk, PID: 14079
E/AndroidRuntime(14079): java.lang.IllegalStateException: Could not execute method for android:onClick
E/AndroidRuntime(14079):        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
E/AndroidRuntime(14079):        at android.view.View.performClick(View.java:4438)
E/AndroidRuntime(14079):        at android.view.View$PerformClick.run(View.java:18422)
E/AndroidRuntime(14079):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(14079):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(14079):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(14079):        at android.app.ActivityThread.main(ActivityThread.java:5019)
E/AndroidRuntime(14079):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14079):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14079):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime(14079):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime(14079):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(14079): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(14079):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14079):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14079):        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
E/AndroidRuntime(14079):        ... 11 more
E/AndroidRuntime(14079): Caused by: java.lang.NullPointerException
E/AndroidRuntime(14079):        at com.didi.virtualapk.MainActivity.onButtonClick(MainActivity.java:108)
E/AndroidRuntime(14079):        ... 14 more
W/ActivityManager(  504):   Force finishing activity com.didi.virtualapk/.core.A$1
W/WindowManager(  504): updateFocusedWindowLocked, focusedAppToken is null.

**Comment by Gundam0079** [comment]
梆梆是通过 自己的编译器解码的 通过vapk加载 是找不到类的因为没有解码
这个问题应该是找梆梆解决 

但是我有一个疑问  **vapk 在插件安全上有什么机制么  校验签名可以加上么？**

**Comment by Gundam0079** [comment]
经过群里的咨询 可以通过验证apk签名的方式  确保加载的apk是 自己打包签名打的
ZipVerifyUtil  test.cer放到本地一份  跟apk中的证书对比 如果一致就认为签名正确
注意checkZipFileForCertificate方法 missing不需要验证  重写一下

**Comment by jingle729** [comment]
apk加载前文件校验是必不可少的，但是怎么有效防止反编译，代码破解。 如果不能保证代码安全，那么比较敏感的等重要信息（加密算法等），就需要在宿主包处理，然后通过进程交互方式调用。

**Comment by superqiaopu** [comment]
自行检查apk的签名
