### ISSUE TITLE
插件Module依赖library Module报错

### ISSUE THREAD

**Issue by 652028815** [didi/VirtualAPK#227]
build.gradle:3.0.0
gradle:4.1-all
build_versions.min_sdk = 15
build_versions.target_sdk = 26
build_versions.compile_sdk = 26
build_versions.build_tools = "26.0.2"

error:
* What went wrong:
java.io.FileNotFoundException: /Users/balance/AndroidStudioProjects/VirtualDemo/library/build/intermediates/intermediate-jars/release/full.jar/AndroidManifest.xml (No such file or directory)
> /Users/balance/AndroidStudioProjects/VirtualDemo/library/build/intermediates/intermediate-jars/release/full.jar/AndroidManifest.xml (No such file or directory)

library打包成aar之后在依赖就没问题了，壳module直接依赖library Module也没问题，library未使用virtualApk（试过像plugin一样的配置，也会有问题）

**Comment by jingle729** [comment]
我也碰到了相同的问题，在尝试解决中。

**Comment by superqiaopu** [comment]
使用新版本。
