### ISSUE TITLE
The directory of host application doesn't exist!

### ISSUE THREAD

**Issue by arlong** [didi/VirtualAPK#23]
Error:A problem occurred configuring project ':app'.
> The directory of host application doesn't exist!

how to config host directory?

**Comment by chenenyu** [comment]
```gradle
virtualAPK {
    ...
    targetHost = '...'
}
```

see [here](https://github.com/didi/VirtualAPK/blob/master/PluginDemo/app/build.gradle).

**Comment by singwhatiwanna** [comment]
参考 [常见问题解答](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
