### ISSUE TITLE
怎样知道插件打包成功了呢？

### ISSUE THREAD

**Issue by nangonghuang** [didi/VirtualAPK#232]
引入apply plugin: 'com.didi.virtualapk.plugin' 并且配置了
```
virtualApk {
    packageId = 0x6f             // The package id of Resources.
    targetHost='../app' // The path of application module in host project.
    applyHostMapping = true      // [Optional] Default value is true.
}
``` 
之后没有报错就是吗？
但是构建插件apk的时候会输出
```
Configuration on demand is an incubating feature.
[INFO][VAPlugin] Evaluating VirtualApk's configurations...
[INFO][VAPlugin] Skipped all VirtualApk's configurations!
```
这些日志，后面调起插件里面的activity的时候，如果是 setContentView(R.layout.activity_main) 会报找不到资源的错误。如果是 setContentView(new TextView(this)); 则没有问题可以调起来。
整个配置的过程就如同[Getting started](https://github.com/didi/VirtualAPK)里面所写
版本是
```
classpath 'com.android.tools.build:gradle:3.0.0'
classpath 'com.didi.virtualapk:gradle:0.9.8.4'
compile 'com.didi.virtualapk:core:0.9.6'
```

**Comment by superqiaopu** [comment]
请先查看相关Wiki：
 [Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
[常见问题解答(不定时更新)](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
