### ISSUE TITLE
为什么Gradle版本一定要为2.14.1？

### ISSUE THREAD

**Issue by Microhx** [didi/VirtualAPK#238]
公司统一的环境是4.1，我使用4.1编译dome发现不能成功；回退到2.14.1之后，发现当前AS支持Gradle版本为4.1，所以想请问一下，我该怎么使用VirtualAPK呢？在后期难道不适配高版本的gradle嘛？ # #

**Comment by superqiaopu** [comment]
因为你用的是旧版本
