### ISSUE TITLE
apply plugin not work at gradle:3.1.2

### ISSUE THREAD

**Issue by wuyisheng** [didi/VirtualAPK#243]
apply plugin not work at gradle:3.1.2 (com.android.tools.build:gradle:3.1.2) , with error:

> Unable to load class 'com.android.build.gradle.internal.TaskContainerAdaptor'.

Downgrade to gradle:3.0.0 can workaround

**Comment by superqiaopu** [comment]
use com.didi.virtualapk:gradle:0.9.8.5-dev or the later version.
