### ISSUE TITLE
宿主中如何使用插件中的类

### ISSUE THREAD

**Issue by Anzhi-Meiying** [didi/VirtualAPK#245]
> **请问一下宿主如何使用插件中的自定义View**

比如宿主需要使用插件中的Fragment，但是看到并没有提供相应的api，然后我使用了如下方法

`Fragment fragment = (Fragment) Class.forName("com.meiying.XFragment",true, loadedPlugin.getClassLoader()).newInstance();`

成功获取到了类，但是**问题**出现了：

> 07-24 22:10:11.037 24933-24933/com.meiying.bug W/ResourceType: **No known package when getting value for resource number 0x6f020010**
> 07-24 22:10:11.038 24933-24933/com.meiying.bug D/AndroidRuntime: Shutting down VM
> 07-24 22:10:11.039 24933-24933/com.meiying.bug E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.meiying.bug, PID: 24933
>     **android.content.res.Resources$NotFoundException: Resource ID #0x6f020010**
>         at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:222)
>         at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:91)
>         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2159)
>         at android.content.res.Resources.getLayout(Resources.java:1157)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
>         at com.mf.plugin.fragment.AboutFragment.onCreateView(XFragment.java:38)
>         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
>         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
>         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
>         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
>         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
>         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
>         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
>         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
>         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
>         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6657)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

看提示是说，插件中的Fragment的R找不到了，这是为什么呢，如果是直接startActivity插件中的活动是可以找到R的

**Comment by Anzhi-Meiying** [comment]
已经解决
通过

> PluginUtil.hookActivityResources(getActivity(), PluginConstants.PLUGIN_PKG);

小米Note3，Android O

**Comment by superqiaopu** [comment]
7.0及以上系统加载插件后再初始化webview 资源hook时效，需要重新hook，或者先初始化webview再加载插件

**Comment by dhlie** [comment]
@superqiaopu 我在Application的onCreate()方法中先new WebView().loadUrl()再加载插件还是不行

**Comment by tangkoucan** [comment]
这样获取fragment 实例 还有 fragment特性吗 ，只能做普通类使用了吧？
如何获取插件的fragment 且有fragment特性呢？

**Comment by tangkoucan** [comment]
> 已经解决
> 通过
> 
> > PluginUtil.hookActivityResources(getActivity(), PluginConstants.PLUGIN_PKG);
> 
> 小米Note3，Android O
这样获取fragment 实例 还有 fragment特性吗 ，只能做普通类使用了吧？
如何获取插件的fragment 且有fragment特性呢？
