### ISSUE TITLE
VAInstrumentation 中 mBase ？

### ISSUE THREAD

**Issue by oogcartoon** [didi/VirtualAPK#247]
1.hook技术替换ActivityThread中的mInstrumentation  ，为什么这里保留了mInstrumentation（mBase）  ，并且在VAInstrumentation很多地方调用 ？
2既然是hook替换，那原来的对象的状态同步怎么处理?
3.既然状态同步没问题，是不是因为在Application里面初始化 PluginManager.getInstance(base).init(); 这时候原来的mInstrumentation没有状态数据，这也是很多框架在Application里面初始化的原因？
谢谢！

**Comment by superqiaopu** [comment]
看Android源码去
