### ISSUE TITLE
插件工程assemblePlugin  报错Failed to notify task execution listener.

### ISSUE THREAD

**Issue by xujiatao1989** [didi/VirtualAPK#250]
按照正常流程配置我自己的插件工程（非demo）后
第一次./gradlew clean assemblePlugin报错信息：
Failed to notify task execution listener.
> org/gradle/internal/impldep/com/google/common/collect/ImmutableList
第二次./gradlew clean assemblePlugin报错信息：
Failed to notify task execution listener.
> Could not initialize class com.didi.virtualapk.utils.PackagingUtils

**Comment by superqiaopu** [comment]
先把demo跑通，然后照着demo配置。

**Comment by zhangyongfa888** [comment]
Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify task execution listener.

**Comment by supermavericks** [comment]
有适配3.2.0的么，测试版本呢？

**Comment by darrenjh** [comment]
我的gradle版本是3.2.1也遇到这个问题，改成3.1.0之后问题解决了
