### ISSUE TITLE
加载插件期间得到进度实现进度条

### ISSUE THREAD

**Issue by sdgSnow** [didi/VirtualAPK#252]
pluginManager.loadPlugin(apk);
                pluginManager.addCallback(new PluginManager.Callback() {
                    @Override
                    public void onAddedLoadedPlugin(LoadedPlugin plugin) {
                    }
                });

听群里大佬说添加这个回调，但是这个回调里面不知道使用哪个去获取当前已加载多少，然后去对比插件apk大小算进度，请问下是这个回调吗还是我搞错了，是其他的，求指教

**Comment by superqiaopu** [comment]
没有详细的进度，有需要可以自己定制。

**Comment by sdgSnow** [comment]
你好，请问下这个定制是咋定制的呢
