### ISSUE TITLE
VirtualAPK vs RePlugin?

### ISSUE THREAD

**Issue by JackyAndroid** [didi/VirtualAPK#26]

**Comment by singwhatiwanna** [comment]
二者的适用场景不同，VirtualAPK侧重于耦合类

**Comment by JackyAndroid** [comment]
"Q：您们和360之前发的DroidPlugin的主要区别是什么？
......
当然，还有一点，就是使用场景的不同：

DroidPlugin解决的是各个独立功能拼装在一起，能够快速发布，不需要有任何的交互。目前市面上的一些双开应用，和DroidPlugin的思路有共同之处。当然了，要做到完整的双开，则仍需要大量的修改，如Native Hook等。

RePlugin解决的是各个功能模块能独立升级，又能需要和宿主之间有一定交互。其宗旨是“允许插件少量修改，来换得最佳稳定和灵活”。"

**RePlugin能做到和宿主之间有一定交互**

刚哥的意思是VirtualAPK在宿主交互方面比RePlugin更强大？
