### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.zk.pluginproject.MainActivity" 

### ISSUE THREAD

**Issue by zk0301** [didi/VirtualAPK#29]
运行官方的示例没有问题。

我自己写了2个项目，按照步骤来做的。点击跳转报错。
targetHost应该填什么啊，绝对路径？相对路径？

**Comment by TheBloodElf** [comment]
一般相对路径，如果你是按照我这样放的插件工程（把插件工程直接复制进宿主工程根目录，就是和宿主工程中app文件夹同级），那么是这样写
![0545716f-11f8-402e-8573-3a99926fc535](https://user-images.githubusercontent.com/16093976/27776490-a847cfba-5fdd-11e7-965f-5fe470cb2770.png)

**Comment by zk0301** [comment]
我是分开的2个项目。
C:\Users\Administrator\Desktop\HostProject
C:\Users\Administrator\Desktop\PluginProject
我是分开编译的，没有用命令行。VirtualAPK-master我也是这样搞的，没问题。
@TheBloodElf

**Comment by TheBloodElf** [comment]
你这样就是360的那种咯，启动插件后插件几乎没有和宿主有交互了

**Comment by zk0301** [comment]
@TheBloodElf 我在issue28也问过你了。我是独立编译的。命令行编译那个我不会。
我觉得文档写的不够详细啊。真实写项目，当然是host和plugin分开写的，分开编译的。你混在一起写，你怎么测试plugin啊。

**Comment by zk0301** [comment]
@TheBloodElf 先不管交互，现在我跳转都报错了，不知道怎么改。。。

**Comment by TheBloodElf** [comment]
我成功了。。。我要看到你的代码才知道问题啊

**Comment by zk0301** [comment]
@TheBloodElf 哥们来个QQ啊

**Comment by TheBloodElf** [comment]
289092194，我的群

**Comment by singwhatiwanna** [comment]
@zk0301 targetHost填写宿主工程Application module的路径（绝对路径或者相对路径都可以），插件工程和宿主工程就是单独的两个工程，插件工程可以随便放在一个目录，不是非得在宿主工程的目录下。

**Comment by zk0301** [comment]
@singwhatiwanna 我试过绝对路径。C:\Users\Administrator\Desktop\HostProject\app  这么写，没对啊。
