### ISSUE TITLE
自己建的新宿主工程，配置好后执行gradle clean iR出错

### ISSUE THREAD

**Issue by TheBloodElf** [didi/VirtualAPK#30]
* What went wrong:
Task 'iR' is ambiguous in root project 'VirtualAPKHost'. Candidates are: 'incrementalDebugAndroidTestJavaCompilationSafeguard', 'incrementalDebugJavaCompilationSafeguard', 'incrementalDebugUnitTestJavaCompilationSafeguard', 'incrementalReleaseJavaCompilationSafeguard', 'incrementalReleaseUnitTestJavaCompilationSafeguard'.

**Comment by singwhatiwanna** [comment]
@TheBloodElf iR其实就是installRelease的缩写，你自己打个release的包即可。

**Comment by TheBloodElf** [comment]
* What went wrong:
Task 'installRelease' not found in root project 'VirtualHost'. Some candidates are: 'uninstallRelease'.

**Comment by TheBloodElf** [comment]
@singwhatiwanna 你的意思是说所有的运行都必须是Release环境吗？

**Comment by TheBloodElf** [comment]
除了官方demo，自己建的怎么都不行，请问是不是有什么神秘代码？

**Comment by singwhatiwanna** [comment]
@TheBloodElf 并没有神秘代码，宿主可以是debug，插件必须是release。你在buildTye里面加个release。VirtualAPK是给公司级的产品用的，公司级的产品，发布的时候肯定是release。

**Comment by TheBloodElf** [comment]
好的，我必须得做出来一个，坚持

**Comment by zk0301** [comment]
@singwhatiwanna 哥们，下载的demo和首页的步骤描述，差太多了吧。话说，我自己建新工程，我也编不过啊。demo的可以。

**Comment by qq634421026** [comment]
@singwhatiwanna 插件release还是不行  assembleReleasePlugin打出的包还是不行

**Comment by zk0301** [comment]
@qq634421026 我的是assembleReleasePlugin，我的可以，哇咔咔

**Comment by qq634421026** [comment]
@zk0301  是自己建立的可以还是demo可以？

**Comment by zk0301** [comment]
@qq634421026 上面写有啊。是demo。

**Comment by qq634421026** [comment]
噢噢 demo啊 我以为你自己写的可以呢
