### ISSUE TITLE
终于编过了

### ISSUE THREAD

**Issue by zk0301** [didi/VirtualAPK#33]
下载的示例有点坑啊，PluginDemo里的targetHost是错的。郁闷。
还有gladle命令行编译，大家都有门槛。
还有首页那个使用步骤也没写清楚，不看了wiki，都不知道怎么编译，还以为是直接run。

**Comment by zk0301** [comment]
还有啊，最好分出来2个project。这样方便大家理解。
现实中plugin是单独开发的，源码嵌进去，感觉怪怪的。

**Comment by zk0301** [comment]
那个我说，我在demo的PluginDemo做减法，只剩下一个MainActivity。
神奇的事情发生了，host点击跳转，会跳到自己。原因是plugin的布局名字layout_main.xml和它重名了！！！
这个巨坑啊！你文档要讲清楚啊

**Comment by zk0301** [comment]
发现另一个问题。
插件虽然改了重新编译，host跳转过去不变。必须杀死host进程重启。操作步骤如下
1.修改text  
2.gradlew clean assemblePlugin 
3.adb push app/build/outputs/apk/app-beijing-release-unsigned.apk /sdcard/Test.apk
4.点击“加载插件”，观察发现文字不变
5.按返回键，退出宿主。再进入，观察发现文字还是不变。
6.按返回键，退出宿主。杀死宿主进程。再进入，观察变了。

**Comment by singwhatiwanna** [comment]
@zk0301 插件构建需要assemblePlugin，这个需要参考下wiki，你提的其他问题，我们会考虑，谢谢你的反馈。

**Comment by syusikoku** [comment]
zk0301 ，你可以把你可以跑的demo分享给我一份吗?xfgczzg@163.com.qq:2475725157,不胜感激
