### ISSUE TITLE
插件是加载成功了 但是跳转插件的activity出现了 java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation这个错误 板子是4.4.4系统的

### ISSUE THREAD

**Issue by xmtggh** [didi/VirtualAPK#34]

**Comment by qq634421026** [comment]
我是加载成功之后跳转出现                                                                            
   Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {online.aroenzhang.virtualapkplugin/online.aroenzhang.virtualapkplugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by xmtggh** [comment]
是的！我自己写了个，和使用个官方的demo出现了相同的错误！直接运行插件app是可以的

**Comment by xmtggh** [comment]
@qq634421026 是的！我自己写了个，和使用个官方的demo出现了相同的错误！直接运行插件app是可以的

**Comment by xmtggh** [comment]
@qq634421026 是的！我自己写了个，和使用个官方的demo出现了相同的错误！直接运行插件app是可以的

**Comment by qq634421026** [comment]
@xmtggh 插件你是怎么打出来的 我的也是插件可以单独安装运行，但是在宿主中跳转插件上的activity时候就报错了

**Comment by xmtggh** [comment]
@qq634421026 直接build出来的 没有签名

**Comment by qq634421026** [comment]
@xmtggh 是常规的build吗 好像这个要 build assemblePlugin这个 我签名也是不好使

**Comment by xmtggh** [comment]
@qq634421026 是的，还是在研究一下 感觉可能是我某个步骤的问题

**Comment by TheBloodElf** [comment]
我现在在官方的demo基础上缩减代码，达到了相当于新建工程那样的代码量；也可以成功实现跳转，之后打算在此缩减demo基础上进行开发，不自己另外新建项目了，因为我试了一天了，还是不知道自己新建的和官方的有什么区别

**Comment by TheBloodElf** [comment]
@xmtggh @qq634421026 宿主app可以直接run进行测试，插件app需要assemblePlugin

**Comment by qq634421026** [comment]
@TheBloodElf 我插件assemblePlugin报错，只能assembleReleasePlugin

**Comment by xmtggh** [comment]
@TheBloodElf clean一下试试 我的成功了 在原来的demo上修改是可以的！自己的demo还是有点问题，你先尝试着跳转官方的！

**Comment by xmtggh** [comment]
@qq634421026 clean一下试试 我的成功了 在原来的demo上修改是可以的！自己的demo还是有点问题，你先尝试着跳转官方的！

**Comment by qq634421026** [comment]
@xmtggh  我自己的demo跳转的时候跳到自己了然后再点久崩了

**Comment by 896442744** [comment]
清理宿主项目重新编译试试

**Comment by hprostudy** [comment]
@qq634421026  请问在Window下使用官方demo（0.9.0），assemblePlugin成功后加载插件也报这个错误是什么情况？你的解决了吗？
