### ISSUE TITLE
gradlew clean assemblePlugin问题

### ISSUE THREAD

**Issue by StiflerJj** [didi/VirtualAPK#35]
VirtualAPK-master>gradlew clean assemblePlugin
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assemblePlugin' not found in root project 'VirtualAPK-master'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by chenenyu** [comment]
`assemblePlugin`是插件工程才有的task
