### ISSUE TITLE
编译插件报错问题（Cannot get property 'id' on null object....）

### ISSUE THREAD

**Issue by ZhangLeiBoy** [didi/VirtualAPK#359]
环境：
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
com.android.tools.build:gradle:3.2.0
插件版本：
com.didi.virtualapk:gradle:0.9.8.6.2-dev
com.didi.virtualapk:core:0.9.9.1-dev

宿主编译没有问题，正常生成了app/build/VAHost
在进行插件编译的时候报了如下错误
插件编译 ./gradlew clean assemblePlugin

![image](https://user-images.githubusercontent.com/11265848/68455860-51f9be80-0237-11ea-8e6f-b440e58e3c00.png)

不知道各位码友是否有遇到同样问题，或解决过类似问题的，请帮忙分析一下。

**Comment by ZhangLeiBoy** [comment]
已解决

**Comment by ghost** [comment]
如何解决的？@Zhang

**Comment by ghost** [comment]
> 已解决

解决方案分销一下吧
