### ISSUE TITLE
能不能加上那个中文的说明

### ISSUE THREAD

**Issue by a1018875550** [didi/VirtualAPK#4]
https://mp.weixin.qq.com/s/lJzNaSmvsxsNw5XtZIBsYg

如果能加上这个中文说明最好了；

**Comment by WuxuFanhua** [comment]
https://github.com/didi/VirtualAPK/wiki
这不是有么

**Comment by Harlber** [comment]
你这个是wiki。。。另外play上不允许这么干了，建议READMD加一份中文说明

**Comment by a1018875550** [comment]
额，我的错。没有电wiki;;
