### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by zengyunpeng** [didi/VirtualAPK#41]
当加载插件的时候,插件是加载成功了但是报错如标题,求教大神这是什么问题

**Comment by zengyunpeng** [comment]
插件里面的activity没有使用appCompat Theme,但是代码我没改动过啊

**Comment by chenenyu** [comment]
插件apk是怎么生成的？

**Comment by sjtuwzx** [comment]
我也遇到了这问题，插件apk是./gradlew assemble生成的

**Comment by chenenyu** [comment]
@zengyunpeng @sjtuwzx `./gradlew assemblePlugin`

**Comment by zengyunpeng** [comment]
@chenenyu 用gradlew assemblePlugin命令报错啊
* What went wrong:
A problem occurred configuring project ':app'.
> The directory of host application doesn't exist!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.618 secs

**Comment by chenenyu** [comment]
> The directory of host application doesn't exist!  

这很明显，插件中配置的`targetHost`不对...  看看PluginDemo中怎么配置的

**Comment by fly7632785** [comment]
同问？   我看了plugindemo里面的theme都是 theme.appcompat的主题  为什么还是不行

**Comment by hlmichael** [comment]
我把pluginDemo里面的BookManagerActivity改成集成Activity就可以了

**Comment by fly7632785** [comment]
@hlmichael  我根据wiki的 命令行方式运行 好了  ， 貌似是如果release版没有问题

**Comment by singwhatiwanna** [comment]
@all 请不要自己找土方法去解决，参考wiki即可。

**Comment by lxj1137800599** [comment]
插件·编译报错**The directory of host application doesn't exist!**
需要把targetHost = '../app'  这样改。
我也不知道为什么，其实原本的写法按照理论来讲是行得通的

**Comment by fendouwangzi** [comment]
@lxj1137800599  你这种方式是对的，完美
