### ISSUE TITLE
hook资源？

### ISSUE THREAD

**Issue by ClaymanTwinkle** [didi/VirtualAPK#42]
![image](https://user-images.githubusercontent.com/15152514/27813552-3ec91cb6-60a9-11e7-915d-9fca8b918bf4.png)
这里为什么api24以上就不执行？

**Comment by singwhatiwanna** [comment]
@ClaymanTwinkle 不需要hook

**Comment by ClaymanTwinkle** [comment]
为什么不需要hook？

**Comment by singwhatiwanna** [comment]
@ClaymanTwinkle read source code, both VirtualAPK and Android
