### ISSUE TITLE
demo加载apk出问题了

### ISSUE THREAD

**Issue by langwan1314** [didi/VirtualAPK#44]
07-05 09:24:08.505 22040-22040/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 22040
                                                                     java.lang.IncompatibleClassChangeError: Structural change of android.support.v4.app.FragmentActivity is hazardous (/data/user/0/com.didi.virtualapk/app_dex/Test.dex at compile time, /data/app/com.didi.virtualapk-1/oat/arm/base.odex at runtime): Virtual method count off: 52 vs 40
                                                                     Landroid/support/v4/app/FragmentActivity; (Compile time):
                                                                      Static fields:
                                                                       Ljava/lang/String; ALLOCATED_REQUEST_INDICIES_TAG
                                                                       Ljava/lang/String; FRAGMENTS_TAG
                                                                       I HONEYCOMB
                                                                       I MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS
                                                                       I MSG_REALLY_STOPPED
                                                                       I MSG_RESUME_PENDING
                                                                       Ljava/lang/String; NEXT_CANDIDATE_REQUEST_INDEX_TAG
                                                                       Ljava/lang/String; REQUEST_FRAGMENT_WHO_TAG
                                                                       Ljava/lang/String; TAG
                                                                      Instance fields:
                                                                       Z mCreated
                                                                       Landroid/support/v4/app/FragmentController; mFragments
                                                                       Landroid/os/Handler; mHandler
                                                                       Landroid/support/v4/media/session/MediaControllerCompat; mMediaController
                                                                       I mNextCandidateRequestIndex
                                                                       Z mOptionsMenuInvalidated
                                                                       Landroid/support/v4/util/SparseArrayCompat; mPendingFragmentActivityResults
                                                                       Z mReallyStopped
                                                                       Z mRequestedPermissionsFromFragment
                                                                       Z mResumed
                                                                       Z mRetaining
                                                                       Z mStopped
                                                                      Direct methods:
                                                                       <init>()V
                                                                       allocateRequestIndex(Landroid/support/v4/app/Fragment;)I
                                                                       dumpViewHierarchy(Ljava/lang/String;Ljava/io/PrintWriter;Landroid/view/View;)V
                                                                       viewToString(Landroid/view/View;)Ljava/lang/String;
                                                                      Virtual methods:
                                                                       dispatchFragmentsOnCreateView(Landroid/view/View;Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;
                                                                       doReallyStop(Z)V
                                                                       dump(Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V
                                                                       getLastCustomNonConfigurationInstance()Ljava/lang/Object;
                                                                       getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
                                                                       getSupportLoaderManager()Landroid/support/v4/app/LoaderManager;
                                                                       getSupportMediaController()Landroid/support/v4/media/session/MediaControllerCompat;
                                                                       onActivityResult(IILandroid/content/Intent;)V
                                                                       onAttachFragment(Landroid/support/v4/app/Fragment;)V
                                                                       onBackPressed()V
                                                                       onConfigurationChanged(Landroid/content/res/Configuration;)V
                                                                       onCreate(Landroid/os/Bundle;)V
                                                                       onCreatePanelMenu(ILandroid/view/Menu;)Z
                                                                       onCreateView(Landroid/view/View;Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;
                                                                       onCreateView(Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;
                                                                       onDestroy()V
                                                                       onLowMemory()V
                                                                       onMenuItemSelected(ILandroid/view/MenuItem;)Z
                                                                       onMultiWindowModeChanged(Z)V
                                                                       onNewIntent(Landroid/content/Intent;)V
                                                                       onPanelClosed(ILandroid/view/Menu;)V
                                                                       onPause()V
                                                                       onPictureInPictureModeChanged(Z)V
                                                                       onPostResume()V
                                                                       onPrepareOptionsPanel(Landroid/view/View;Landroid/view/Menu;)Z
                                                                       onPreparePanel(ILandroid/view/View;Landroid/view/Menu;)Z
                                                                       onReallyStop()V
                                                                       onRequestPermissionsResult(I[Ljava/lang/String;[I)V
                                                                       onResume()V
                                                                       onResumeFragments()V
                                                                       onRetainCustomNonConfigurationInstance()Ljava/lang/Object;
                                                                       onRetainNonConfigurationInstance()Ljava/lang/Object;
                                                                       onSaveInstanceState(Landroid/os/Bundle;)V
                                                                       onStart()V
                                                                       onStateNotSaved()V
                                                                       onStop()V
                                                                       requestPermissionsFromFragment(Landroid/support/v4/app/Fragment;[Ljava/lang/String;I)V
                                                                       setEnterSharedElementCallback(Landroid/support/v4/app/SharedElementCallback;)V
                                                                       setExitSharedElementCallback(Landroid/support/v4/app/SharedElementCallback;)V
                                                                       setSupportMediaController(Landroid/support/v4/media/session/MediaControllerCompat;)V
                                                                       startActivityForResult(Landroid/content/Intent;I)V
                                                                       startActivityForResult(Landroid/content/Intent;ILandroid/os/Bundle;)V
                                                                       startActivityFromFragment(Landroid/support/v4/app/Fragment;Landroid/content/Intent;I)V
                                                                       startActivityFromFragment(Landroid/support/v4/app/Fragment;Landroid/content/Intent;ILandroid/os/Bundle;)V
                                                                       startIntentSenderForResult(Landroid/content/IntentSender;ILandroid/content/Intent;III)V
                                                                       startIntentSenderForResult(Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V
07-05 09:24:08.505 22040-22040/com.didi.virtualapk E/AndroidRuntime:   startIntentSenderFromFragment(Landroid/support/v4/app/Fragment;Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V
                                                                       supportFinishAfterTransition()V
                                                                       supportInvalidateOptionsMenu()V
                                                                       supportPostponeEnterTransition()V
                                                                       supportStartPostponedEnterTransition()V
                                                                       validateRequestPermissionsRequestCode(I)V
                                                                     Landroid/support/v4/app/FragmentActivity; (Runtime):
                                                                      Static fields:
                                                                       Ljava/lang/String; FRAGMENTS_TAG
                                                                       I HONEYCOMB
                                                                       I MSG_REALLY_STOPPED
                                                                       I MSG_RESUME_PENDING
                                                                       Ljava/lang/String; TAG
                                                                      Instance fields:
                                                                       Landroid/support/v4/util/SimpleArrayMap; mAllLoaderManagers
                                                                       Z mCheckedForLoaderManager
                                                                       Landroid/support/v4/app/FragmentContainer; mContainer
                                                                       Z mCreated
                                                                       Landroid/support/v4/app/FragmentManagerImpl; mFragments
                                                                       Landroid/os/Handler; mHandler
                                                                       Landroid/support/v4/app/LoaderManagerImpl; mLoaderManager
                                                                       Z mLoadersStarted
                                                                       Z mOptionsMenuInvalidated
                                                                       Z mReallyStopped
                                                                       Z mResumed
                                                                       Z mRetaining
                                                                       Z mStopped
                                                                      Direct methods:
                                                                       <init>()V
                                                                       dumpViewHierarchy(Ljava/lang/String;Ljava/io/PrintWriter;Landroid/view/View;)V
                                                                       viewToString(Landroid/view/View;)Ljava/lang/String;
                                                                      Virtual methods:
                                                                       doReallyStop(Z)V
                                                                       dump(Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V
                                                                       getLastCustomNonConfigurationInstance()Ljava/lang/Object;
                                                                       getLoaderManager(Ljava/lang/String;ZZ)Landroid/support/v4/app/LoaderManagerImpl;
                                                                       getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
                                                                       getSupportLoaderManager()Landroid/support/v4/app/LoaderManager;
                                                                       invalidateSupportFragment(Ljava/lang/String;)V
                                                                       onActivityResult(IILandroid/content/Intent;)V
                                                                       onAttachFragment(Landroid/support/v4/app/Fragment;)V
                                                                       onBackPressed()V
                                                                       onConfigurationChanged(Landroid/content/res/Configuration;)V
                                                                       onCreate(Landroid/os/Bundle;)V
                                                                       onCreatePanelMenu(ILandroid/view/Menu;)Z
                                                                       onCreateView(Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;
                                                                       onDestroy()V
                                                                       onKeyDown(ILandroid/view/KeyEvent;)Z
                                                                       onLowMemory()V
                                                                       onMenuItemSelected(ILandroid/view/MenuItem;)Z
                                                                       onNewIntent(Landroid/content/Intent;)V
                                                                       onPanelClosed(ILandroid/view/Menu;)V
                                                                       onPause()V
                                                                       onPostResume()V
                                                                       onPrepareOptionsPanel(Landroid/view/View;Landroid/view/Menu;)Z
                                                                       onPreparePanel(ILandroid/view/View;Landroid/view/Menu;)Z
                                                                       onReallyStop()V
                                                                       onResume()V
                                                                       onResumeFragments()V
                                                                       onRetainCustomNonConfigurationInstance()Ljava/lang/Object;
                                                                       onRetainNonConfigurationInstance()Ljava/lang/Object;
                                                                       onSaveInstanceState(Landroid/os/Bundle;)V
                                                                       onStart()V
                                                                       onStop()V
                                                                       setEnterSharedElementCallback(Landroid/support/v4/app/SharedElementCallback;)V
                                                                       setExitSharedElementCallback(Landroid/support/v4/app/SharedElementCallback;)V
                                                                       startActivityForResult(Landroid/content/Intent;I)V
                                                                       startActivityFromFragment(Landroid/support/v4/app/Fragment;Landroid/content/Intent;I)V
                                                                       supportFinishAfterTransition()V
                                                                       supportInvalidateOptionsMenu()V
                                                                       supportPostponeEnterTransition()V
                                                                       supportStartPostponedEnterTransition()V
                                                                      (declaration of 'com.leaves.mentalitydoctor.activity.BaseActivity' appears in /storage/emulated/0/Test.apk)
                                                                         at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                         at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:101)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2811)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6692)
07-05 09:24:08.505 22040-22040/com.didi.virtualapk E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by XiuLin** [comment]
请按照官方流程正确构建。
