### ISSUE TITLE
跳转插件，有切换效果，但是限制宿主界面

### ISSUE THREAD

**Issue by VeryCure** [didi/VirtualAPK#46]
loadPlugin成功，点击按钮跳转到插件MainActivity，可以看出activity得切换效果，但是显示还是宿主得展示数据，这是怎么回事？麻烦解答下

**Comment by AllenCoder** [comment]
1. 宿主app的布局id不能和 插件app的布局id 名字相同，否则会默认覆盖
2. 建议卸载后，更好名字重试
