### ISSUE TITLE
不支持x86架构？模拟器运行不了，lib包只有arm的

### ISSUE THREAD

**Issue by fly7632785** [didi/VirtualAPK#47]
不支持x86架构？模拟器运行不了，lib包只有arm的

**Comment by fly7632785** [comment]
![e7f392de-d293-4a9e-9200-207f5c4950db](https://user-images.githubusercontent.com/10276266/27895341-c6ba3b22-6244-11e7-9620-7b2fbdd00759.png)
手动复制了一波 应该管用

**Comment by danieldaydan** [comment]
在app gradle文件中的`defaultConfig {
        applicationId "com.didi.virtualapk"
        minSdkVersion 15
        targetSdkVersion 15
        versionCode 3
        versionName "1.0.0"
    }`加上 ` ndk {
            // 指定要ndk需要兼容的架构(这样其他依赖包里mips,x86,armeabi-v7a,arm64-v8之类的so会被过滤掉)
            abiFilters "armeabi,x86"
        }`
然后gradle.properties文件中加入android.useDeprecatedNdk=true

**Comment by superqiaopu** [comment]
这个so没用，可以删掉。
