### ISSUE TITLE
virtualApk中的targetHost应该配置什么

### ISSUE THREAD

**Issue by CyjAndroid** [didi/VirtualAPK#48]
virtualApk {
    packageId = 0x6f 
    targetHost = 'VirtualAPK/app' 
    applyHostMapping = true
}

这样是不行的

**Comment by OsBelief** [comment]
virtualApk {
    packageId = 0x6f // the package id of Resources.
    targetHost = '../../VirtualAPK/app' // the path of application module in host project.
    applyHostMapping = true //optional, default value: true.
}

**Comment by CyjAndroid** [comment]
这个是指宿主工程app的路径么？那我写的VirtualAPK/app应该没问题啊

**Comment by CyjAndroid** [comment]
写项目全路径就ok了
