### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by JsonYuu** [didi/VirtualAPK#5]
Error:org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>

**Comment by dodola** [comment]
@JsonYuu 你需要使用 gradle-2.14.1-all.zip

**Comment by achellies** [comment]
不能提供一下gradlew。。。

**Comment by chenenyu** [comment]
@achellies 已提供。

**Comment by time1982** [comment]
Thank.
