### ISSUE TITLE
编译报错：ManifestDependency 把命令换一下

### ISSUE THREAD

**Issue by danieldaydan** [didi/VirtualAPK#52]
构建报错的构建插件时报错Failed to notify project evaluation listener com/android/builder/dependency/ManifestDependency
可以把命令换一下
gradle clean assembleRelease---> ./gradlew clean assembleRelease
gradle clean assemblePlugin--->./gradlew clean assemblePlugin
换了后可以正常编译

**Comment by singwhatiwanna** [comment]
这是因为Gradle版本的问题，建议用2.14.1

**Comment by cuijg** [comment]
你gradle版本是多少啊

**Comment by danieldaydan** [comment]
@cuijg   我自己安装的gradle版本是3.5   这个是给出现这个问题的人参考下   因为gradlew包装器绑定的特定版本的gradle，与项目的是一致的，构建的时候可以确保使用正确的Gradle版本

**Comment by singwhatiwanna** [comment]
参考 [常见问题解答](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
