### ISSUE TITLE
找不到插件so

### ISSUE THREAD

**Issue by zzjthl** [didi/VirtualAPK#56]
已在插件中指定VA_IS_HAVE_LIB为true,插件apk中也有so文件。
插件apk：
![libs](https://user-images.githubusercontent.com/7536458/27951090-4c1734f4-6336-11e7-92f0-bc4be04d2311.PNG)
插件Activity加载so异常: 
 FATAL EXCEPTION: main
                                                                        Process: com.pb.partybuildandroid, PID: 4354
                                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pb.partybuildandroid-1/base.apk", zip file "/storage/emulated/0/document/live.apk"],nativeLibraryDirectories=[/data/app/com.pb.partybuildandroid-1/lib/arm, /system/fake-libs, /data/app/com.pb.partybuildandroid-1/base.apk!/lib/armeabi-v7a, /data/user/0/com.pb.partybuildandroid/app_valibs, /system/lib, /vendor/lib]]] couldn't find "libyuv.so"
                                                                            at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                            at java.lang.System.loadLibrary(System.java:1530)

**Comment by singwhatiwanna** [comment]
@zzjthl 按如下步骤核对下：
1. 解压插件apk，看里面是否有so
2. 查看这个目录【/data/user/0/com.pb.partybuildandroid/app_valibs】，看里面是否有so

**Comment by zzjthl** [comment]
@singwhatiwanna  感谢你来解答我的问题:
1.插件apk解压后是有so的
2./data/user/0/com.pb.partybuildandroid/app_valibs为空

**Comment by singwhatiwanna** [comment]
@zzjthl 那就是so没有copy过去，按如下步骤确认：
1. 反编译插件apk，看其manifest文件中application节点下是否有VA_IS_HAVE_LIB；
2. debug下so的copy过程，看为何没有copy即可

**Comment by wuketidai** [comment]
```
if((findSo && entry.getName().contains("lib/" + cpuArch)) || (!findSo && entry.getName().contains("lib/armeabi/")))
```

倘若找不到当前机子最适的 arch，会尝试去找 armeabi，但是我的项目默认是带 armeabi-v7a, 所以建议也是在 application 里面配置默认带的 arch，copy so 的时候尝试读取即可。

**Comment by wuketidai** [comment]
#99 我提交了这个 pr 你可以试试

**Comment by superqiaopu** [comment]
新版对匹配最合适arch的逻辑做了优化。请关注dev分支。
