### ISSUE TITLE
请问Host和Plugin工程有什么特别注意的吗?

### ISSUE THREAD

**Issue by liujixi1992** [didi/VirtualAPK#67]
DEMO可以正常跑起来，自己按照wiki步骤建的Host和Plugin工程为什么总是not load =_=

**Comment by AllenCoder** [comment]
注意一下问题：
1. demo工程的 **targetSdkVersion 22** 很好的规避了v23以上的动态权限要求，这个自己写demo时容易忽视
2. demo要自己配置读写权限 ，默认新建的demo配置任何权限
3. 宿主工程的xml 的id和插件xml的id 不能相同，否则会出现默认被宿主覆盖
4. gradle版本暂时建议和Demo保持一致 **2.14.1**
5.  targetHost = '../../VirtualAPK/app' // 检测这个路径是否正确，相对路径或者绝对路径都行

**Comment by cjxqhhh** [comment]
![image](https://user-images.githubusercontent.com/13252720/28619206-d81d891e-7239-11e7-8218-3fe655e877b1.png)
这里，插件要依赖宿主的信息？如果宿主和插件是两个不同的开发商要怎么办？
