### ISSUE TITLE
我想知道插件工程怎么调用宿主工程的代码，有demo么？

### ISSUE THREAD

**Issue by caokunhk** [didi/VirtualAPK#70]
我想知道插件工程怎么调用宿主工程的代码，有demo么？在官方的demo工程里没找到相关的案例。

**Comment by singwhatiwanna** [comment]
@caokunhk [点击这里](https://github.com/didi/VirtualAPK/wiki/VirtualAPK-%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)

**Comment by luying6** [comment]
@singwhatiwanna 有其它的方式吗？
