### ISSUE TITLE
提个问题

### ISSUE THREAD

**Issue by CarGuo** [didi/VirtualAPK#74]
项目中 AndroidStub 说是为了避免反射造成性能损失，在CoreLibrary中看到的使用应该还是反射，可以问下Stub使用在哪个地方吗？

**Comment by singwhatiwanna** [comment]
部分隐藏API用到了Stub，没用通过反射。

**Comment by CarGuo** [comment]
不好意思，刚刚脑子没转过来，像ActivityThread这种····抱歉抱歉
