### ISSUE TITLE
Execution failed for task ':app:processReleaseResources'

### ISSUE THREAD

**Issue by songmeitao** [didi/VirtualAPK#77]
D:\code\projects\NewsPlugin>gradle clean assemblePlugin
Incremental java compilation is an incubating feature.                                        
:clean                                                                              
:app:clean                
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:preDebugBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72221Library                 
:app:prepareComAndroidSupportDesign2221Library
:app:prepareComAndroidSupportSupportV42221Library                 
:app:prepareReleaseDependencies
:app:compileReleaseAidl
:app:compileReleaseRenderscript                 
:app:generateReleaseBuildConfig                 
:app:mergeReleaseShaders
:app:compileReleaseShaders
:app:generateReleaseAssets
:app:mergeReleaseAssets                 
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources
:app:mergeReleaseResources                 
:app:processReleaseManifest
Ignore all manifests of com.android.support:appcompat-v7:22.2.1
Ignore all manifests of com.android.support:appcompat-v7:22.2.1
Ignore all manifests of com.android.support:support-v4:22.2.1
:app:processReleaseResources FAILED          
              
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> java.io.EOFException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get m
ore log output.

BUILD FAILED

Total time: 11.142 secs

**Comment by chenenyu** [comment]
Need more info. try `gradlew.bat clean assemblePlugin --stacktrace`

**Comment by zhangchaoqun** [comment]
麻烦，想问楼主解决了吗，怎么解决的？？

**Comment by XiuLin** [comment]
@songmeitao @zhangchaoqun 将插件中的buildToolsVersion试着提高到"23.0.3"以上试试，我的是这样解决的。
