### ISSUE TITLE
支持自带插件在assets 目录吗？

### ISSUE THREAD

**Issue by JsonYuu** [didi/VirtualAPK#8]
支持自带插件在assets 中，调用方法加载吗？

**Comment by dodola** [comment]
@JsonYuu 你需要从assets里拷贝出来到一个目录里才行

**Comment by JsonYuu** [comment]
也就是说现在不支持在assets 中自带插件直接加载对吧？

**Comment by singwhatiwanna** [comment]
@JsonYuu 将插件从assets中释放出来，这不属于VirtualAPK框架的范畴，你可以自行释放插件到文件系统中。
