### ISSUE TITLE
compile the pluginDemo went to wrong using "sh make.sh"

### ISSUE THREAD

**Issue by ChengKeven** [didi/VirtualAPK#80]
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com/android/builder/dependency/ManifestDependency

**Comment by singwhatiwanna** [comment]
@ChengKeven 参考 [常见问题解答](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)

**Comment by akingyin1987** [comment]
我也遇到了这个问题，但改了路径没用呀，还是会出现

**Comment by superqiaopu** [comment]
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
