### ISSUE TITLE
是否能支持fragment插件

### ISSUE THREAD

**Issue by tz-xiaomage** [didi/VirtualAPK#82]
fragment作为插件，与宿主activity有一定的交互
activity负责显示隐藏fragment，fragment能有参调用Activity的一两个方法，请问支持吗？能否给个demo呢？感谢。

**Comment by Stone305585** [comment]
楼上想用插件，给宿主activity添加插件里面的fragment??我就问一下

**Comment by wilsonssss** [comment]
"给宿主activity添加插件里面的fragment", exactly what i need

**Comment by tz-xiaomage** [comment]
@Stone305585 是的

**Comment by tz-xiaomage** [comment]
@wilsonssss 你解决了吗？

**Comment by llp** [comment]
"给宿主activity添加插件里面的fragment", exactly what i need

**Comment by XiuLin** [comment]
可以支持

**Comment by hidetag** [comment]
@wilsonssss 你好，你解决了吗？
