### ISSUE TITLE
遇到让为Activity设置主题的错误，解决方法是将BookManagerActivity的父类给为Activity.

### ISSUE THREAD

**Issue by lypandroidex** [didi/VirtualAPK#83]
由于现在Android4.4以下的已灭绝，所以建议不考虑兼容问题。直接使用Activity避免这些兼容性问题出现。

**Comment by singwhatiwanna** [comment]
你按照wiki中来构建插件，就可以了，你这样改法是不对的。

**Comment by BeEagle** [comment]
@singwhatiwanna @lypandroidex 按wiki 来构建，会报上面主题的错；这种改法可以成功。

**Comment by fendouwangzi** [comment]
需要把targetHost = '../app' 这样改。

**Comment by ihanbo** [comment]
三星s7 跑demo报主题错误 android7.0
