### ISSUE TITLE
插件能跳转，但是页面显示不出来

### ISSUE THREAD

**Issue by wqnmlgbe** [didi/VirtualAPK#86]
我这边按照文档自己写了两个工程，调试后现在能跳转到插件的Activity，但是发现插件的界面一片空白，onCreate方法通过日志观察是调用了的，并且插件的布局文件命名已改为plugin_activity_main，和宿主也不会存在名字冲突，不知道啥原因造成的，求解答

**Comment by HuChundong** [comment]
是不是使用了宿主的动画文件？可以试试去掉动画，直接 startActivity

**Comment by wqnmlgbe** [comment]
宿主跳转代码就是模仿demo写的，直接startActivity。
插件的界面也很简单，就是两个TextView，但是跳转过去后页面就是一片空白，并且标题也成了宿主的标题了

**Comment by BeEagle** [comment]
@wqnmlgbe 你的现在ok 么？我这边也是出现白板，但是生命周期走了。

**Comment by XiuLin** [comment]
如果已经去重还是无法打开 请加入官方交流群 发送相关异常demo

**Comment by keven0632** [comment]
使用 gradlew clean assemblePlugin 生成插件，或者用 AndroidStudio 右侧的 Gradle 按钮下的插件工程下的 assemblePlugin 按钮生成插件，先要 build 宿主一下，然后再生成插件
