### ISSUE TITLE
求官方交流社区群

### ISSUE THREAD

**Issue by fuzhengchao** [didi/VirtualAPK#9]
如题

**Comment by singwhatiwanna** [comment]
VirtualAPK项目通过issue和pr来协作和交流，目前没有交流群。

**Comment by TheBloodElf** [comment]
289092194 我自己建立了一个群，但是如果发出来不合法，我马上撤回该消息

**Comment by singwhatiwanna** [comment]
@TheBloodElf 你用你的个人名义，不要以VirtualAPK官方的名义即可，即不能说是VirtualAPK的官方交流群。
