### ISSUE TITLE
Error:Execution failed for task ':app_plugin:transformClassesAndResourcesWithStrippedForRelease'. > Cannot cast object 'null' with class 'org.codehaus.groovy.runtime.NullObject' to class 'java.util.Set'

### ISSUE THREAD

**Issue by BeEagle** [didi/VirtualAPK#96]
Error:Execution failed for task ':app_plugin:transformClassesAndResourcesWithStrippedForRelease'.
> Cannot cast object 'null' with class 'org.codehaus.groovy.runtime.NullObject' to class 'java.util.Set'

**Comment by yan1234** [comment]
hello, i see the same problem, do you solved it ?

**Comment by superqiaopu** [comment]
--stacktrace
