### ISSUE TITLE
是否支持热修复

### ISSUE THREAD

**Issue by huxiaotian123** [didi/VirtualAPK#97]
如题

**Comment by luying6** [comment]
宿主你可以就放一个壳Activity，然后模块都用插件进行开发，这样也能达到热修复的效果

**Comment by slksir** [comment]
插件化技术不是用来做热修复用的。如果需要热修复功能建议使用其他的热修复方案。腾讯、阿里好像都有实现方案。

**Comment by singwhatiwanna** [comment]
@huxiaotian123 已经插件化的模块天热支持热修复，只需要从服务端下载插件即可。

**Comment by easternHong** [comment]
@singwhatiwanna 
host出bug需要热更新，怎么解决？
